/** The Keyboard shortcuts text: sections of [keys, what they do]. Keys stay under `keyWidth` columns (help.ts). */
export const helpSections: [string, [string, string][]][] = [
  [
    "ESSENTIALS",
    [
      ["Typing", "a session in view has its reply editor open: letters type, Enter sends"],
      ["Esc", "leaves the editor or closes a dialog; drafts are kept"],
      ["Enter", "opens the primary action; sends from the editor"],
      ["n · f", "new session · reply"],
      ["Up · Down", "walk your earlier prompts in an empty editor"],
      ["Esc Esc", "stops the running turn and its tasks; when idle, opens undo"],
      ["x · /stop", "stops it and cancels its tasks at once; /kill confirms, even when idle"],
      ["Shift+Enter", "adds a line (Alt+Enter too); Ctrl+S also sends"],
      ["F4", "discard local draft"],
      ["/ · Ctrl+P", "commands in the conversation or editor · all actions"],
      ["/ · @ · !", "in a message: slash commands · file mentions · a shell command"],
      ["Ctrl+C", "closes a form or stops a running session and its tasks; repeat to quit"],
      ["q", "quits the dashboard; repeat if drafts are unsent or a turn runs"],
      ["Ctrl+H", "hides the screen behind an anvil until a click, Esc or Ctrl+H"],
    ],
  ],
  [
    "SESSION VIEWS",
    [
      ["d", "Changes: uncommitted, branch, or last turn (m switches); @ mentions a file"],
      ["e", "Files: browse and read; Enter opens a folder, ← goes up, @ mentions"],
      ["T", "the session's shared terminal (the agent uses it too)"],
      ["t", "Tasks and to-dos"],
      ["u", "queued messages: Enter sends now, Ctrl+E edits"],
      ["w · H · i", "swarm room (lanes, entries, Tab to post) · harness · details"],
      ["/tools · /trace", "the agent's tools and MCP servers · the event log"],
      ["Context", "the editor's hint row shows the context window: ctx 45%"],
      ["Ctrl+O", "in the transcript: shows or folds long tool output"],
    ],
  ],
  [
    "TERMINALS AND AUTOMATIONS",
    [
      ["2", "Terminals: Enter attaches full-screen, Ctrl+] detaches"],
      ["a · R · d", "new terminal · rename · close"],
      ["3", "Automations: Enter manages (run now, pause, edit, runs, delete)"],
      ["a · E · d", "new automation (every 30m, every 1d, or cron) · edit · delete"],
    ],
  ],
  [
    "TEAM",
    [
      ["4", "Team: rooms in the sidebar, the selected room's log, posts go to its teammates"],
      ["Enter · f", "post to the room: Enter posts, Shift/Alt+Enter adds a line, F4 discards"],
      ["@", "in a post lists the room's teammates; Tab or Enter completes, Esc closes the list"],
      ["t", "the room's tasks: Enter opens the session, c cancels, r refreshes"],
      ["a · E · d", "new room · edit its name and topic · archive, restore or delete (typed word)"],
      ["M", "teammates: Enter menu (edit, pause, stop work, duties, latest session), a add"],
      ["duties", "Enter opens it in Automations, r runs it, a assigns an automation, n creates one"],
      ["F", "factory: s settings · Ctrl+R run · x stop · t trigger · Enter a run's tasks"],
      ["A · [ · r", "show archived rooms · older messages · refresh"],
    ],
  ],
  [
    "SETTINGS AND INTEL",
    [
      [
        ",",
        "Settings: providers, usage and limits, extensions, memories, agents' default models, permission checks and saved rules, servers, appearance",
      ],
      ["Extensions", "Enter on/off · s secret · c setting · o sign in"],
      ["Memories", "a add · E edit · Ctrl+D twice within 2.5 s deletes"],
      ["I", "Intel: advisories, known-exploited CVEs, news; m list · f feeds · p poll"],
      ["Ctrl+P", "then Stop all agents (or /stop-all) interrupts every running session on the server"],
    ],
  ],
  [
    "SERVERS AND HARNESS",
    [
      ["s", "or click the server name opens the server picker"],
      [
        "This computer",
        "the running TurenOS app first, then this host's quick-connect or persistent server, or a private forge serve",
      ],
      ["Picker", "Enter connect · a add URL or user@host · d remove · r rescan"],
      ["SSH", "servers need key or agent login; the TUI opens its own tunnel"],
      ["Passwords", "are asked once and kept only until you quit"],
      [
        "H · /harness",
        "the session's harness tools, guidance, and reviewer proposals; every change confirms with Ctrl+S",
      ],
    ],
  ],
  [
    "FILES AND SHELL",
    [
      ["@", "searches the server's files; Up/Down choose, Tab or Enter completes, Esc closes the list"],
      ["@folder", "keeps searching; a file ends the mention"],
      ["@path#12", "or @path#12-40 attaches only those lines"],
      ["", "The server reads mentioned files; this client does not"],
      ["!", "at the start of a message runs a server shell command; its output arrives as a transcript message"],
    ],
  ],
  [
    "DASHBOARD (no form or search open)",
    [
      ["Ctrl+K", "switch session · Alt+Left/Right hop"],
      ["/", "commands in the conversation; find or filter in the sidebar"],
      ["Ctrl+X · t", "subagent browser · Tasks"],
      ["1 · 2 · 3 · 4", "Sessions · Terminals · Automations · Team"],
      ["Up/Down", "select; Enter focuses the conversation, then replies"],
      ["Tab", "switches panes (Shift+Tab back); b / Ctrl+B sidebar"],
      ["PgUp/PgDn", "scroll a page · r refresh"],
      ["h · [ · ]", "History / Recent · older · newer history page"],
      ["i", "session and connection details"],
      ["Ctrl+Y", "or right-click copies selected text; F6 toggles terminal native selection and its right-click menu"],
      ["tmux", "Ctrl+B twice sends the sidebar shortcut"],
    ],
  ],
  [
    "IN THE REPLY EDITOR",
    [
      ["Ctrl+D", "deletes forward"],
      ["Ctrl+K", "deletes to line end (Esc first to switch session)"],
      ["Ctrl+A", "line start; Alt+Left/Right word motion"],
      ["F2 · Ctrl+G", "or /editor composes the draft in $EDITOR"],
      ["Ctrl+P · Ctrl+X", "also work from the reply; Esc first for Alt+Left/Right"],
      ["Ctrl+N", "new session; also works in drafts and the switcher"],
      ["Tab", "next field (Shift+Tab previous); click Settings reveals launch settings"],
      ["Reply", "Ctrl+T Steer/Queue before sending · PgUp/PgDn reads the conversation"],
      ["Ctrl+O", "in a failed launch form: opens the attempted session"],
      ["", "Drafts last until quit; discard does not stop server work."],
    ],
  ],
  [
    "IN PICKERS AND MODELS",
    [
      ["Up/Down", "choose · Enter select · Esc back"],
      [
        "Sessions",
        "type anytime; Tab Recent / All / Archived (Shift+Tab back); F3 older and Shift+F3 newer title search",
      ],
      ["PgUp/PgDn", "or the wheel browse; click a result to open"],
      ["Ctrl+O", "in the session picker: open an older session by ID"],
      ["t · Ctrl+P", "Tasks · rename, archive/restore, delete, or open parent"],
      ["m · Ctrl+L", "session model · model in New session"],
      ["Tab", "New session settings: folder, agent, model, new git worktree"],
      ["/agent", "chooses the agent; /compact confirms summarization"],
      ["Models", "F2 provider setup · Ctrl+R refresh"],
      ["Providers", "Enter continue/save · Ctrl+U clear key; credentials and configuration are server-global"],
    ],
  ],
  [
    "REQUESTS",
    [
      ["Undo/Redo", "Ctrl+D shows the staged patch before confirming"],
      ["p · o · x", "permission · question · stop the session and its tasks"],
      [
        "Permission",
        "opens on Reject; 1 Reject · 2 Allow once · 3 Allow always answer at once, and Allow always saves the server's rule; arrows then Ctrl+S also send",
      ],
      ["Questions", "arrows choose · Space toggles multiple · Enter selects/continues · Left/Right changes question"],
      ["Review", "answers, then Enter / Ctrl+S sends"],
      ["Custom", "answer: Enter saves · Ctrl+B back to choices"],
      ["Ctrl+R", "opens rejection; Ctrl+S confirms"],
      ["Kill", "/kill: type kill · Ctrl+S confirm"],
      ["Esc", "closes without responding; PgUp/PgDn scrolls forms"],
    ],
  ],
]
