//! Unit tests: hand-constructed pages/headers plus the committed fixture
//! databases under `test/fixtures/` (generated by `test/gen-fixtures.sh`).

use serde_json::Value;

use crate::db::{
    free_regions, read_payload, table_leaf_cell, walk_table_btree, BtreePage, Db,
};
use crate::record::{self, serial_size};
use crate::{varint, Report};

const SIMPLE: &[u8] = include_bytes!("../test/fixtures/simple.db");
const WITHOUT_ROWID: &[u8] = include_bytes!("../test/fixtures/without-rowid.db");
const OVERFLOW: &[u8] = include_bytes!("../test/fixtures/overflow.db");
const DELETED: &[u8] = include_bytes!("../test/fixtures/deleted.db");
const CORRUPT: &[u8] = include_bytes!("../test/fixtures/corrupt.db");
const WAL: &[u8] = include_bytes!("../test/fixtures/wal.db");
const UTF16: &[u8] = include_bytes!("../test/fixtures/utf16.db");
const EMPTY: &[u8] = include_bytes!("../test/fixtures/empty.db");
const MANY: &[u8] = include_bytes!("../test/fixtures/many.db");

fn report() -> Report {
    Report::new()
}

fn parse(v: &str) -> Value {
    serde_json::from_str(v).unwrap()
}

fn ok(v: &str) -> Value {
    let value = parse(v);
    assert_eq!(value["schema_version"], 1, "{v}");
    assert!(value.get("error").is_none(), "{v}");
    value
}

fn err(v: &str) -> String {
    let value = parse(v);
    assert_eq!(value["schema_version"], 1, "{v}");
    value["error"].as_str().unwrap().to_string()
}

// ---- synthetic database builders -----------------------------------------

/// Minimal 100-byte header for a synthetic db.
fn synth_header(page_size: u16, db_pages: u32) -> Vec<u8> {
    let mut h = vec![0u8; 100];
    h[..16].copy_from_slice(b"SQLite format 3\0");
    h[16..18].copy_from_slice(&page_size.to_be_bytes());
    h[18] = 1;
    h[19] = 1;
    h[20] = 0;
    h[21] = 64;
    h[22] = 32;
    h[23] = 32;
    h[24..28].copy_from_slice(&1u32.to_be_bytes()); // change counter
    h[28..32].copy_from_slice(&db_pages.to_be_bytes());
    h[40..44].copy_from_slice(&1u32.to_be_bytes()); // schema cookie
    h[44..48].copy_from_slice(&4u32.to_be_bytes()); // schema format
    h[56..60].copy_from_slice(&1u32.to_be_bytes()); // utf-8
    h[92..96].copy_from_slice(&1u32.to_be_bytes()); // version valid for
    h[96..100].copy_from_slice(&3051000u32.to_be_bytes());
    h
}

/// Encode a SQLite varint.
fn put_varint(out: &mut Vec<u8>, value: u64) {
    if value > 0x00ff_ffff_ffff_ffff {
        // 9-byte form: 8 groups of 7 bits, then all 8 bits of the last byte.
        let mut bytes = [0x80u8; 9];
        bytes[8] = value as u8;
        let mut v = value >> 8;
        for i in (0..8).rev() {
            bytes[i] = 0x80 | (v as u8 & 0x7f);
            v >>= 7;
        }
        out.extend_from_slice(&bytes);
        return;
    }
    let mut groups = [0u8; 8];
    let mut n = 0usize;
    let mut v = value;
    loop {
        groups[7 - n] = (v & 0x7f) as u8;
        n += 1;
        v >>= 7;
        if v == 0 {
            break;
        }
    }
    for i in 8 - n..8 {
        let mut b = groups[i];
        if i != 7 {
            b |= 0x80;
        }
        out.push(b);
    }
}

/// A table-leaf page (type 13). `cells` are `(rowid, record_payload)`; the
/// cell pointer array and content area are laid out per spec.
fn leaf_table_page(page_size: usize, base: usize, cells: &[(i64, Vec<u8>)]) -> Vec<u8> {
    let mut page = vec![0u8; page_size];
    let hdr = base + 8;
    let mut content_start = page_size;
    for (i, (rowid, payload)) in cells.iter().enumerate() {
        let mut cell = Vec::new();
        put_varint(&mut cell, payload.len() as u64);
        put_varint(&mut cell, *rowid as u64);
        cell.extend_from_slice(payload);
        content_start -= cell.len();
        page[content_start..content_start + cell.len()].copy_from_slice(&cell);
        let ptr = hdr + i * 2;
        page[ptr..ptr + 2].copy_from_slice(&(content_start as u16).to_be_bytes());
    }
    page[base] = 13;
    page[base + 3..base + 5].copy_from_slice(&(cells.len() as u16).to_be_bytes());
    page[base + 5..base + 7].copy_from_slice(&(content_start as u16).to_be_bytes());
    page
}

/// An interior table page (type 5): cells are `(child_page, rowid)`.
fn interior_table_page(
    page_size: usize,
    base: usize,
    cells: &[(u32, i64)],
    right: u32,
) -> Vec<u8> {
    let mut page = vec![0u8; page_size];
    let hdr = base + 12;
    let mut content_start = page_size;
    for (i, (child, rowid)) in cells.iter().enumerate() {
        let mut cell = Vec::new();
        cell.extend_from_slice(&child.to_be_bytes());
        put_varint(&mut cell, *rowid as u64);
        content_start -= cell.len();
        page[content_start..content_start + cell.len()].copy_from_slice(&cell);
        let ptr = hdr + i * 2;
        page[ptr..ptr + 2].copy_from_slice(&(content_start as u16).to_be_bytes());
    }
    page[base] = 5;
    page[base + 3..base + 5].copy_from_slice(&(cells.len() as u16).to_be_bytes());
    page[base + 5..base + 7].copy_from_slice(&(content_start as u16).to_be_bytes());
    page[base + 8..base + 12].copy_from_slice(&right.to_be_bytes());
    page
}

/// Assemble a synthetic db: header + numbered pages. Page constructors are
/// called with `base` = b-tree header offset (100 for page 1); for page 1 we
/// copy the bytes after that offset into the file.
fn synth_db(page_size: usize, pages: Vec<(u32, Vec<u8>)>) -> Vec<u8> {
    let count = pages.iter().map(|p| p.0).max().unwrap_or(1) as usize;
    let mut db = vec![0u8; page_size * count];
    db[..100].copy_from_slice(&synth_header(page_size as u16, count as u32));
    for (number, page) in pages {
        let start = (number as usize - 1) * page_size;
        let base = if number == 1 { 100 } else { 0 };
        let len = page.len().saturating_sub(base);
        db[start + base..start + base + len].copy_from_slice(&page[base..]);
    }
    db
}

/// A record payload from serial types + bodies.
fn record(serials: &[(u64, &[u8])]) -> Vec<u8> {
    let mut serial_bytes = Vec::new();
    for (s, _) in serials {
        put_varint(&mut serial_bytes, *s);
    }
    // Header length includes its own varint; test records stay under 128.
    let hlen = serial_bytes.len() + 1;
    assert!(hlen < 128);
    let mut out = vec![hlen as u8];
    out.extend_from_slice(&serial_bytes);
    for (_, body) in serials {
        out.extend_from_slice(body);
    }
    out
}

fn synth_db_for_records() -> Vec<u8> {
    // One-page db whose page 1 is a valid empty leaf — enough for Db::parse.
    let page = leaf_table_page(4096, 100, &[]);
    synth_db(4096, vec![(1, page)])
}

// ---- varint ---------------------------------------------------------------

#[test]
fn varint_single_and_multi_byte() {
    assert_eq!(varint(&[0x00]), Some((0, 1)));
    assert_eq!(varint(&[0x7f]), Some((127, 1)));
    assert_eq!(varint(&[0x81, 0x00]), Some((128, 2)));
    assert_eq!(varint(&[0x81, 0x7f]), Some((255, 2)));
    assert_eq!(varint(&[0xff]), None); // continuation bit set, slice ends
    // 8 bytes with all continuation bits → needs the 9th byte.
    assert_eq!(varint(&[0xff; 8]), None);
}

#[test]
fn varint_nine_byte_max_and_negative_rowid() {
    // 9 x 0xff is the maximum u64 (rowid -1 as i64).
    assert_eq!(varint(&[0xff; 9]), Some((u64::MAX, 9)));
    assert_eq!(varint(&[0xff; 9]).unwrap().0 as i64, -1);
    // 0x80..0x80 (8 bytes) then 0x00 → zero.
    let mut bytes = [0x80u8; 9];
    bytes[8] = 0;
    assert_eq!(varint(&bytes), Some((0, 9)));
    // Trailing bytes are not consumed.
    let mut padded = vec![0x2a];
    padded.extend_from_slice(&[0xaa, 0xbb]);
    assert_eq!(varint(&padded), Some((42, 1)));
}

// ---- serial types / records ------------------------------------------------

#[test]
fn serial_size_table() {
    assert_eq!(serial_size(0), Some(0));
    assert_eq!(serial_size(1), Some(1));
    assert_eq!(serial_size(2), Some(2));
    assert_eq!(serial_size(3), Some(3));
    assert_eq!(serial_size(4), Some(4));
    assert_eq!(serial_size(5), Some(6));
    assert_eq!(serial_size(6), Some(8));
    assert_eq!(serial_size(7), Some(8));
    assert_eq!(serial_size(8), Some(0));
    assert_eq!(serial_size(9), Some(0));
    assert_eq!(serial_size(10), None);
    assert_eq!(serial_size(11), None);
    assert_eq!(serial_size(12), Some(0)); // empty blob
    assert_eq!(serial_size(13), Some(0)); // empty text
    assert_eq!(serial_size(14), Some(1)); // blob(1)
    assert_eq!(serial_size(15), Some(1)); // text(1)
    assert_eq!(serial_size(13 + 2 * 10), Some(10));
    assert_eq!(serial_size(12 + 2 * 20), Some(20));
}

#[test]
fn record_all_serial_types() {
    let bytes = synth_db_for_records();
    let db = Db::parse(&bytes).unwrap();
    let payload = record(&[
        (0, &[]),                              // null
        (1, &[0xfe]),                          // int8  = -2
        (2, &[0x80, 0x00]),                    // int16 = -32768
        (3, &[0xff, 0xff, 0xff]),              // int24 = -1
        (4, &[0x7f, 0xff, 0xff, 0xff]),        // int32 = 2147483647
        (5, &[0xff, 0xff, 0xff, 0xff, 0xff, 0xff]), // int48 = -1
        (6, &[0x80, 0, 0, 0, 0, 0, 0, 0]),     // int64 = i64::MIN
        (7, &[0x3f, 0xf0, 0, 0, 0, 0, 0, 0]),  // real 1.0
        (8, &[]),                              // literal 0
        (9, &[]),                              // literal 1
        (13 + 2 * 3, b"abc"),                  // text(3)
        (12 + 2 * 4, &[0xde, 0xad, 0xbe, 0xef]), // blob(4)
    ]);
    let mut r = report();
    let values = record::decode_record(&db, &payload, 8, &mut r).unwrap();
    assert_eq!(values.len(), 12);
    assert_eq!(values[0]["type"], "null");
    assert_eq!(values[1]["value"], -2);
    assert_eq!(values[2]["value"], -32768);
    assert_eq!(values[3]["value"], -1);
    assert_eq!(values[4]["value"], 2147483647);
    assert_eq!(values[5]["value"], -1);
    assert_eq!(values[6]["value"], i64::MIN);
    assert_eq!(values[7]["value"], 1.0);
    assert_eq!(values[8]["value"], 0);
    assert_eq!(values[9]["value"], 1);
    assert_eq!(values[10]["value"], "abc");
    assert_eq!(values[10]["type"], "text");
    assert_eq!(values[11]["type"], "blob");
    assert_eq!(values[11]["length"], 4);
    assert_eq!(values[11]["previewHex"], "deadbeef");
}

#[test]
fn record_reserved_serial_types_rejected() {
    let bytes = synth_db_for_records();
    let db = Db::parse(&bytes).unwrap();
    for serial in [10u64, 11] {
        let payload = record(&[(serial, &[])]);
        let mut r = report();
        assert_eq!(
            record::decode_record(&db, &payload, 0, &mut r),
            Err("reserved_serial_type")
        );
    }
}

#[test]
fn record_header_malformed() {
    let bytes = synth_db_for_records();
    let db = Db::parse(&bytes).unwrap();
    let mut r = report();
    // header length varint exceeds payload.
    assert_eq!(
        record::decode_record(&db, &[0x7f, 0x00], 0, &mut r),
        Err("record_header")
    );
    // header length cuts inside a multi-byte serial varint.
    assert_eq!(
        record::decode_record(&db, &[0x02, 0x81], 0, &mut r),
        Err("record_header")
    );
    // valid header (serial 128 = 58-byte blob) but body missing.
    assert_eq!(
        record::decode_record(&db, &[0x03, 0x81, 0x00], 0, &mut r),
        Err("record_body")
    );
    // empty payload.
    assert_eq!(
        record::decode_record(&db, &[], 0, &mut r),
        Err("record_header")
    );
}

// ---- header / inspect -------------------------------------------------------

#[test]
fn header_fields_simple() {
    let v = ok(&crate::sqlite_inspect(SIMPLE, "{}"));
    assert_eq!(v["kind"], "sqlite3");
    let h = &v["header"];
    assert_eq!(h["magicOk"], true);
    assert_eq!(h["pageSize"], 4096);
    assert_eq!(h["writeVersion"], 1);
    assert_eq!(h["readVersion"], 1);
    assert_eq!(h["textEncoding"]["name"], "utf-8");
    assert_eq!(h["userVersion"], 7);
    assert_eq!(h["applicationId"], 1337);
    assert_eq!(h["schemaFormat"], 4);
    assert_eq!(h["autovacuum"], false);
    assert_eq!(v["journalMode"], "rollback");
    assert_eq!(v["pages"]["pagesInFile"], 5);
    assert_eq!(v["pages"]["fileSizeIsMultiple"], true);
    assert!(v["flags"].as_array().unwrap().is_empty());
}

#[test]
fn header_wal_mode_and_utf16() {
    let v = ok(&crate::sqlite_inspect(WAL, "{}"));
    assert_eq!(v["journalMode"], "wal");
    assert_eq!(v["header"]["writeVersion"], 2);
    assert_eq!(v["header"]["readVersion"], 2);

    let u = ok(&crate::sqlite_inspect(UTF16, "{}"));
    assert_eq!(u["header"]["textEncoding"]["name"], "utf-16le");
}

#[test]
fn header_corrupt_flags_and_clean_error() {
    let v = ok(&crate::sqlite_inspect(CORRUPT, "{}"));
    assert_eq!(v["header"]["magicOk"], false);
    assert_eq!(v["header"]["pageSize"], Value::Null);
    let flags: Vec<&str> = v["flags"]
        .as_array()
        .unwrap()
        .iter()
        .map(|f| f.as_str().unwrap())
        .collect();
    assert!(flags.contains(&"bad_magic"), "{v}");
    assert!(flags.contains(&"bad_page_size"), "{v}");
    // Page-dependent ops return a clean error, not a panic.
    assert_eq!(err(&crate::sqlite_schema(CORRUPT, "{}")), "invalid_page_size");
    assert_eq!(
        err(&crate::sqlite_rows(CORRUPT, "{\"table\":\"t\"}")),
        "invalid_page_size"
    );
}

#[test]
fn header_db_size_mismatch_flag() {
    // Valid header claiming 9 pages but the file holds 3.
    let page = leaf_table_page(512, 100, &[]);
    let mut db = synth_db(512, vec![(1, page), (2, vec![]), (3, vec![])]);
    db[28..32].copy_from_slice(&9u32.to_be_bytes());
    let v = ok(&crate::sqlite_inspect(&db, "{}"));
    let flags: Vec<&str> = v["flags"]
        .as_array()
        .unwrap()
        .iter()
        .map(|f| f.as_str().unwrap())
        .collect();
    assert!(flags.contains(&"db_size_mismatch"), "{v}");
    assert_eq!(v["pages"]["pagesInFile"], 3);
}

#[test]
fn inspect_too_small_and_bad_magic() {
    assert_eq!(err(&crate::sqlite_inspect(&[0u8; 50], "{}")), "not_sqlite");
    // Bad magic but valid page size: parses best-effort.
    let page = leaf_table_page(4096, 100, &[]);
    let mut db = synth_db(4096, vec![(1, page)]);
    db[0] = b'X';
    let v = ok(&crate::sqlite_inspect(&db, "{}"));
    assert_eq!(v["kind"], "sqlite3");
    assert_eq!(v["header"]["magicOk"], false);
}

// ---- schema walk -------------------------------------------------------------

#[test]
fn schema_walk_simple() {
    let v = ok(&crate::sqlite_schema(SIMPLE, "{}"));
    let records = v["records"].as_array().unwrap();
    let by_name = |n: &str| records.iter().find(|r| r["name"] == n).unwrap();
    assert_eq!(by_name("users")["type"], "table");
    assert_eq!(by_name("meta")["type"], "table");
    assert_eq!(by_name("idx_users_age")["type"], "index");
    assert_eq!(by_name("idx_users_age")["tblName"], "users");
    assert_eq!(by_name("v_users")["type"], "view");
    assert_eq!(by_name("v_users")["rootpage"], 0);
    assert_eq!(by_name("trg_users")["type"], "trigger");
    assert!(by_name("users")["sql"]
        .as_str()
        .unwrap()
        .contains("CREATE TABLE users"));
    assert_eq!(v["recordCount"], records.len());
}

#[test]
fn schema_max_items_cap() {
    let v = ok(&crate::sqlite_schema(SIMPLE, "{\"maxItems\":2}"));
    assert_eq!(v["records"].as_array().unwrap().len(), 2);
    assert_eq!(v["truncated"], true);
    assert!(v["totalRecords"].as_u64().unwrap() > 2);
}

#[test]
fn schema_utf16_database() {
    // sqlite_master itself is stored in the database encoding.
    let v = ok(&crate::sqlite_schema(UTF16, "{}"));
    let records = v["records"].as_array().unwrap();
    assert_eq!(records[0]["name"], "t");
    assert_eq!(records[0]["type"], "table");
    assert!(records[0]["sql"]
        .as_str()
        .unwrap()
        .contains("CREATE TABLE t"));
}

// ---- rows -------------------------------------------------------------------

fn user_row(rows: &[Value], rowid: i64) -> Value {
    rows.iter().find(|r| r["rowid"] == rowid).unwrap().clone()
}

#[test]
fn rows_simple_all_types() {
    let v = ok(&crate::sqlite_rows(SIMPLE, "{\"table\":\"users\",\"maxRows\":256}"));
    let rows = v["rows"].as_array().unwrap();
    assert_eq!(rows.len(), 4);
    assert_eq!(v["withoutRowid"], false);
    // rowid order
    assert_eq!(rows[0]["rowid"], 1);
    let r1 = user_row(rows, 1);
    let vals = r1["values"].as_array().unwrap();
    // INTEGER PRIMARY KEY is a rowid alias: the record stores NULL.
    assert_eq!(vals[0]["type"], "null");
    assert_eq!(vals[1]["value"], "alice");
    assert_eq!(vals[2]["value"], 30);
    assert_eq!(vals[3]["value"], 91.5);
    assert_eq!(vals[4]["type"], "blob");
    assert_eq!(vals[4]["length"], 6);
    assert_eq!(vals[4]["previewHex"], "0102deadbeef");
    let r3 = user_row(rows, 3);
    let vals3 = r3["values"].as_array().unwrap();
    assert_eq!(vals3[3]["type"], "null"); // score NULL
    let r4 = user_row(rows, 4);
    let vals4 = r4["values"].as_array().unwrap();
    assert_eq!(vals4[2]["value"], -7); // negative int
    assert_eq!(vals4[4]["length"], 12); // zeroblob(12)
    assert_eq!(v["columnNames"][1], "name");
}

#[test]
fn rows_caps_and_selectors() {
    let v = ok(&crate::sqlite_rows(SIMPLE, "{\"table\":\"users\",\"maxRows\":2}"));
    assert_eq!(v["rows"].as_array().unwrap().len(), 2);
    assert_eq!(v["truncated"], true);
    // maxRows clamps to 256.
    let v2 = ok(&crate::sqlite_rows(
        SIMPLE,
        "{\"table\":\"users\",\"maxRows\":9999}",
    ));
    assert_eq!(v2["maxRows"], 256);
    assert_eq!(err(&crate::sqlite_rows(SIMPLE, "{}")), "missing_table");
    assert_eq!(
        err(&crate::sqlite_rows(SIMPLE, "{\"table\":\"nope\"}")),
        "table_not_found"
    );
    assert_eq!(
        err(&crate::sqlite_rows(SIMPLE, "{\"table\":\"v_users\"}")),
        "not_a_table"
    );
}

#[test]
fn rows_without_rowid_table() {
    let v = ok(&crate::sqlite_rows(
        WITHOUT_ROWID,
        "{\"table\":\"dict\",\"maxRows\":10}",
    ));
    assert_eq!(v["withoutRowid"], true);
    let rows = v["rows"].as_array().unwrap();
    assert_eq!(rows.len(), 3);
    // Index b-tree: no rowid; records decode PK-first.
    for row in rows {
        assert_eq!(row["rowid"], Value::Null);
    }
    let words: Vec<&str> = rows
        .iter()
        .map(|r| r["values"][0]["value"].as_str().unwrap())
        .collect();
    // Key order in the index b-tree.
    assert_eq!(words, ["apple", "mid", "zinc"]);
}

#[test]
fn rows_overflow_chain_blob_and_text() {
    let v = ok(&crate::sqlite_rows(
        OVERFLOW,
        "{\"table\":\"big\",\"maxRows\":10}",
    ));
    let rows = v["rows"].as_array().unwrap();
    assert_eq!(rows.len(), 3);
    let r1 = user_row(rows, 1);
    let blob = &r1["values"][1];
    assert_eq!(blob["type"], "blob");
    assert_eq!(blob["length"], 4000);
    // sha256 of 4000 zero bytes.
    assert_eq!(
        blob["sha256"],
        "fc19b1997119425765295aeab72d76faa6927d4f83985d328c26f20468d6cc76"
    );
    let r3 = user_row(rows, 3);
    let text = &r3["values"][1];
    assert_eq!(text["type"], "text");
    assert_eq!(text["length"], 3000);
    assert!(text["value"].as_str().unwrap().starts_with("abab"));
}

// ---- table stats --------------------------------------------------------------

#[test]
fn table_stats_simple() {
    let v = ok(&crate::sqlite_table_stats(
        SIMPLE,
        "{\"table\":\"users\"}",
    ));
    let t = &v["tables"][0];
    assert_eq!(t["table"], "users");
    assert_eq!(t["rows"], 4);
    assert_eq!(t["depth"], 1);
    assert_eq!(t["rowid"]["min"], 1);
    assert_eq!(t["rowid"]["max"], 4);
    assert_eq!(t["pages"]["leaf"], 1);
    assert_eq!(t["corrupt"], false);
}

#[test]
fn table_stats_interior_pages() {
    // many.db forces interior pages (300 rows on 512-byte pages).
    let v = ok(&crate::sqlite_table_stats(MANY, "{\"table\":\"nums\"}"));
    let t = &v["tables"][0];
    assert_eq!(t["rows"], 300);
    assert!(t["depth"].as_u64().unwrap() >= 2, "{t}");
    assert!(t["pages"]["interior"].as_u64().unwrap() >= 1, "{t}");
    assert_eq!(t["rowid"]["min"], 1);
    assert_eq!(t["rowid"]["max"], 300);
    // All tables walk.
    let all = ok(&crate::sqlite_table_stats(MANY, "{}"));
    assert!(all["tables"].as_array().unwrap().len() >= 1);
}

#[test]
fn table_stats_overflow_pages() {
    let v = ok(&crate::sqlite_table_stats(OVERFLOW, "{\"table\":\"big\"}"));
    let t = &v["tables"][0];
    assert!(t["pages"]["overflow"].as_u64().unwrap() >= 8, "{t}");
    assert_eq!(t["cellsWithOverflow"], 3);
}

// ---- freelist ------------------------------------------------------------------

#[test]
fn freelist_chain_deleted_db() {
    let v = ok(&crate::sqlite_freelist(DELETED, "{}"));
    assert_eq!(v["declaredFreePages"], 6);
    assert_eq!(v["countedFreePages"], 6);
    assert_eq!(v["countMatchesDeclared"], true);
    assert_eq!(v["broken"], false);
    assert!(v["trunkCount"].as_u64().unwrap() >= 1);
    assert!(v["carving"]["totalCarvableBytes"].as_u64().unwrap() > 1024);
    let trunks = v["trunks"].as_array().unwrap();
    assert_eq!(trunks[0]["page"], 4);
}

#[test]
fn freelist_cycle_detected() {
    let mut bytes = DELETED.to_vec();
    // Point the trunk page (page 4, 1024-byte pages) at itself.
    let trunk_off = 3 * 1024;
    bytes[trunk_off..trunk_off + 4].copy_from_slice(&4u32.to_be_bytes());
    let v = ok(&crate::sqlite_freelist(&bytes, "{}"));
    assert_eq!(v["broken"], true);
    assert!(v["warnings"]
        .as_array()
        .unwrap()
        .iter()
        .any(|w| w.as_str().unwrap().contains("cycle")));
}

#[test]
fn freelist_out_of_range_link() {
    let mut bytes = DELETED.to_vec();
    // Next trunk pointer → far beyond the file.
    let trunk_off = 3 * 1024;
    bytes[trunk_off..trunk_off + 4].copy_from_slice(&9999u32.to_be_bytes());
    let v = ok(&crate::sqlite_freelist(&bytes, "{}"));
    assert_eq!(v["broken"], true);
}

// ---- carving --------------------------------------------------------------------

#[test]
fn carve_finds_dropped_table_rows() {
    let v = ok(&crate::sqlite_carve(DELETED, "{\"maxCandidates\":4096}"));
    assert_eq!(v["heuristic"], true);
    let text = v.to_string();
    assert!(text.contains("scratch-row-111"), "{text}");
    assert!(text.contains("scratch-row-222"), "{text}");
    let regions: Vec<&str> = v["candidates"]
        .as_array()
        .unwrap()
        .iter()
        .map(|c| c["region"].as_str().unwrap())
        .collect();
    assert!(regions
        .iter()
        .any(|r| r.starts_with("freelist") || *r == "freeblock" || *r == "unallocated"));
    for c in v["candidates"].as_array().unwrap() {
        assert!(c["confidence"].as_f64().unwrap() > 0.0);
        assert_eq!(c["heuristic"], true);
    }
}

#[test]
fn carve_respects_candidate_cap() {
    let v = ok(&crate::sqlite_carve(DELETED, "{\"maxCandidates\":3}"));
    assert_eq!(v["candidates"].as_array().unwrap().len(), 3);
    assert_eq!(v["truncated"], true);
}

#[test]
fn carve_probe_rejects_noise() {
    // All-zero and all-0xff regions produce no candidates.
    let mut page = vec![0u8; 512];
    assert!(record::probe_record_header(&page).is_none());
    page.fill(0xff);
    assert!(record::probe_record_header(&page).is_none());
    // A real record probes cleanly.
    let payload = record(&[(1, &[7]), (13 + 2 * 3, b"abc")]);
    let (hlen, serials) = record::probe_record_header(&payload).unwrap();
    assert_eq!(hlen, 3);
    assert_eq!(serials, vec![1, 19]);
}

// ---- traversal internals ----------------------------------------------------------

#[test]
fn btree_interior_walk_and_right_pointer() {
    // page 1: interior with cell (child=2,rowid=1) + right pointer 3.
    // pages 2,3: leaves with rows {1} and {2,3}.
    let p1 = interior_table_page(512, 100, &[(2, 1)], 3);
    let p2 = leaf_table_page(512, 0, &[(1, record(&[(0, &[])]))]);
    let p3 = leaf_table_page(
        512,
        0,
        &[(2, record(&[(0, &[])])), (3, record(&[(0, &[])]))],
    );
    let db = synth_db(512, vec![(1, p1), (2, p2), (3, p3)]);
    let d = Db::parse(&db).unwrap();
    let mut seen = Vec::new();
    let mut r = report();
    let stats = walk_table_btree(&d, 1, &mut r, |page, off| {
        let cell = table_leaf_cell(&d, page, off).unwrap();
        seen.push(cell.rowid);
        true
    });
    assert_eq!(seen, [1, 2, 3]); // in-order traversal incl. right pointer
    assert_eq!(stats.depth, 2);
    assert_eq!(stats.leaf_pages, 2);
    assert_eq!(stats.interior_pages, 1);
    assert_eq!(stats.min_rowid, Some(1));
    assert_eq!(stats.max_rowid, Some(3));
}

#[test]
fn btree_cycle_detected() {
    // Interior page whose right pointer is itself.
    let p1 = interior_table_page(512, 100, &[], 1);
    let db = synth_db(512, vec![(1, p1)]);
    let d = Db::parse(&db).unwrap();
    let mut r = report();
    let stats = walk_table_btree(&d, 1, &mut r, |_, _| true);
    assert_eq!(stats.cycles, vec![1]);
    assert!(r
        .warnings
        .iter()
        .any(|w| w.contains("cycle")));
}

#[test]
fn btree_negative_rowid_and_page_one_base() {
    // Page 1 leaf with rowid -1 (9-byte varint) and a big rowid.
    let p1 = leaf_table_page(
        4096,
        100,
        &[(-1, record(&[(0, &[])])), (i64::MAX, record(&[(8, &[])]))],
    );
    let db = synth_db(4096, vec![(1, p1)]);
    let d = Db::parse(&db).unwrap();
    let mut seen = Vec::new();
    let mut r = report();
    walk_table_btree(&d, 1, &mut r, |page, off| {
        seen.push(table_leaf_cell(&d, page, off).unwrap().rowid);
        true
    });
    assert_eq!(seen, [-1, i64::MAX]);
}

#[test]
fn freeblock_regions_and_unallocated() {
    // Leaf page with one live cell at the end and free space: free_regions
    // reports the unallocated gap.
    let p = leaf_table_page(512, 100, &[(1, record(&[(0, &[])]))]);
    let db = synth_db(512, vec![(1, p)]);
    let d = Db::parse(&db).unwrap();
    let page = d.page(1).unwrap();
    let btree = BtreePage::parse(&page).unwrap();
    let mut r = report();
    let regions = free_regions(&page, &btree, &mut r);
    assert_eq!(regions.len(), 1);
    assert_eq!(regions[0].kind, "unallocated");
    // Gap runs from end of the cell pointer array to content start.
    assert_eq!(regions[0].offset, 100 + 8 + 2);
    assert!(regions[0].len > 300);
}

#[test]
fn overflow_payload_bad_link_flagged() {
    // Overflow pointer outside the file: truncated, warned, never panics.
    let p = leaf_table_page(512, 100, &[]);
    let db = synth_db(512, vec![(1, p)]);
    let d = Db::parse(&db).unwrap();
    let mut r = report();
    let out = read_payload(&d, b"abc", 7777, 100, &mut r).unwrap();
    assert_eq!(out.complete, false);
    assert_eq!(out.truncated, true);
    assert_eq!(&out.bytes, b"abc");
    assert!(r.warnings.iter().any(|w| w.contains("out of range")));
}

// ---- guard rails --------------------------------------------------------------------

#[test]
fn guard_errors() {
    assert_eq!(err(&crate::sqlite_inspect(&[], "{}")), "empty_input");
    assert_eq!(
        err(&crate::sqlite_inspect(SIMPLE, &"{".repeat(5000))),
        "options_too_large"
    );
    assert_eq!(
        err(&crate::sqlite_inspect(SIMPLE, "{nope")),
        "invalid_options"
    );
    assert_eq!(
        err(&crate::sqlite_inspect(&vec![0u8; 33 * 1024 * 1024], "{}")),
        "input_too_large"
    );
}

#[test]
fn truncated_and_tiny_inputs_no_panic() {
    for cut in [100usize, 200, 4096 + 10, SIMPLE.len() - 1] {
        let v = parse(&crate::sqlite_schema(&SIMPLE[..cut], "{}"));
        assert_eq!(v["schema_version"], 1);
    }
    // Truncated mid-page still parses header.
    let v = ok(&crate::sqlite_inspect(&SIMPLE[..500], "{}"));
    assert_eq!(v["header"]["magicOk"], true);
    assert!(v["flags"]
        .as_array()
        .unwrap()
        .iter()
        .any(|f| *f == "short_first_page" || *f == "trailing_partial_page" || *f == "db_size_mismatch"));
}

#[test]
fn empty_database_valid() {
    let v = ok(&crate::sqlite_schema(EMPTY, "{}"));
    assert_eq!(v["recordCount"], 1);
    assert_eq!(v["records"][0]["name"], "t");
    let rows = ok(&crate::sqlite_rows(EMPTY, "{\"table\":\"t\"}"));
    assert_eq!(rows["rowCount"], 0);
}

#[test]
fn utf16_rows_decoded() {
    let v = ok(&crate::sqlite_rows(UTF16, "{\"table\":\"t\",\"maxRows\":10}"));
    let rows = v["rows"].as_array().unwrap();
    assert_eq!(rows.len(), 1);
    assert_eq!(rows[0]["values"][0]["value"], "héllo");
    assert_eq!(rows[0]["values"][1]["value"], 5);
}
