name: Bug report
description: Report a reproducible problem in TurenOS
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug you encountered
      placeholder: What happened?
    validations:
      required: true

  - type: input
    id: plugins
    attributes:
      label: Plugins
      description: What plugins are you using?
    validations:
      required: false

  - type: input
    id: forge-version
    attributes:
      label: TurenOS version
      description: What version of TurenOS are you using?
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false

  - type: textarea
    id: screenshot-or-link
    attributes:
      label: Screenshot
      description: Attach a screenshot if it helps explain the problem
      placeholder: Drag and drop a screenshot here
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: what OS are you using?
      placeholder: e.g., macOS 26.0.1, Ubuntu 22.04, Windows 11
    validations:
      required: false

  - type: input
    id: terminal
    attributes:
      label: Terminal
      description: what terminal are you using?
      placeholder: e.g., iTerm2, Ghostty, Alacritty, Windows Terminal
    validations:
      required: false
