import { mkdir } from "node:fs/promises"
import path from "node:path"
import { Extension } from "@turenlabs/schema"
import { validateCatalogPolicy, validateManifestPolicy } from "../src/validate"
import { Schema } from "effect"

const root = path.resolve(import.meta.dir, "..")
const source = path.resolve(root, "../../services/catalog/manifests")
const decode = Schema.decodeUnknownSync(Extension.Manifest)
const files = [...new Bun.Glob("**/*.json").scanSync({ cwd: source, absolute: true })].toSorted()
const values = await Promise.all(
  files.map(async (file) => ({ file: path.relative(source, file), value: JSON.parse(await Bun.file(file).text()) })),
)
const manifests = values.map((item) => decode(item.value))

const ids = new Set<string>()
const adapters = new Set<string>()
for (const manifest of manifests) {
  validateManifestPolicy(manifest)
  if (ids.has(manifest.id)) throw new Error(`Duplicate extension id: ${manifest.id}`)
  ids.add(manifest.id)
  for (const contribution of manifest.contributions) {
    if (adapters.has(contribution.adapter)) throw new Error(`Duplicate extension adapter: ${contribution.adapter}`)
    adapters.add(contribution.adapter)
  }
}
validateCatalogPolicy(manifests)

const output = `// Generated by script/generate.ts. Do not edit.\nimport { Extension } from "@turenlabs/schema"\nimport { Schema } from "effect"\n\nconst decode = Schema.decodeUnknownSync(Extension.Manifest)\n\nexport const manifests = [\n${values
  .map((item) => `  // ${item.file}\n  decode(${JSON.stringify(item.value)}),`)
  .join("\n")}\n] as const\n`
const destination = path.join(root, "src/generated.ts")

if (process.argv.includes("--check")) {
  if ((await Bun.file(destination).text()) !== output) throw new Error("Extension catalog is not generated")
  process.exit(0)
}

await mkdir(path.dirname(destination), { recursive: true })
await Bun.write(destination, output)
