import { expect, test } from "bun:test"
import { createTestRenderer } from "@opentui/core/testing"
import { mountDashboard } from "../src/index"
import { cleanup, waitForFrame, leaveComposer, fixture } from "./dashboard-fixture"

test("oversized paste is rejected before insertion and submitting freezes the draft", async () => {
  const server = fixture({ postDelay: 100 })
  const view = await createTestRenderer({ width: 110, height: 38 })
  cleanup.push(() => view.renderer.destroy())
  const app = mountDashboard(view.renderer, server.connection, server.server.url.href)
  await app.ready
  view.mockInput.pressKey("n")
  await waitForFrame(view, (frame) => frame.includes("What would you like to do?"))
  await view.mockInput.pasteBracketedText("x".repeat(32001))
  await view.renderOnce()
  expect(view.captureCharFrame()).toContain("Paste a shorter message")
  await view.mockInput.typeText("Inspect the server")
  view.mockInput.pressKey("s", { ctrl: true })
  await view.mockInput.typeText("do not append")
  await view.mockInput.pasteBracketedText("nor paste")
  view.mockInput.pressKey("k", { ctrl: true })
  view.mockInput.pressArrow("right", { meta: true })
  view.mockInput.pressKey("F4")
  view.mockInput.pressEscape()
  view.mockInput.pressKey("s", { ctrl: true })
  await Bun.sleep(250)
  await waitForFrame(view, (frame) => frame.includes("Task sent."))
  expect(server.posts).toHaveLength(2)
  expect(server.posts[1]?.body).toMatchObject({ prompt: { text: "Inspect the server" } })
})

test("failed agent discovery cannot launch using a blank directory", async () => {
  const server = fixture({ agentStatus: 500 })
  const view = await createTestRenderer({ width: 110, height: 38 })
  cleanup.push(() => view.renderer.destroy())
  const app = mountDashboard(view.renderer, server.connection, server.server.url.href)
  await app.ready
  view.mockInput.pressKey("n")
  await waitForFrame(view, (frame) => frame.includes("Cannot load agents"))
  await view.mockInput.typeText("Inspect the server")
  view.mockInput.pressTab()
  view.mockInput.pressKey("a", { ctrl: true })
  for (let index = 0; index < 12; index++) view.mockInput.pressKey("DELETE")
  view.mockInput.pressKey("s", { ctrl: true })
  await waitForFrame(view, (frame) => frame.includes("Enter an absolute directory"))
  expect(server.posts).toHaveLength(0)
})

test("failed agent discovery reads as one sentence, replaces the loading row, and names a typed folder", async () => {
  const server = fixture({ agentStatus: 500 })
  const view = await createTestRenderer({ width: 110, height: 38 })
  cleanup.push(() => view.renderer.destroy())
  await mountDashboard(view.renderer, server.connection, server.server.url.href).ready
  view.mockInput.pressKey("n")
  const frame = await waitForFrame(view, (text) => text.includes("Cannot load agents"))
  expect(frame.replace(/\s*│\s*\n\s*│\s*/g, " ")).toContain("check the server logs. Ctrl+S retries.")
  expect(frame).not.toContain("..")
  view.mockInput.pressTab()
  await waitForFrame(view, (text) => text.includes("Agents unavailable"))
  expect(view.captureCharFrame()).not.toContain("Loading agents")
  view.mockInput.pressKey("a", { ctrl: true })
  for (let index = 0; index < 12; index++) view.mockInput.pressKey("DELETE")
  await view.mockInput.typeText("/srv/nope")
  view.mockInput.pressTab()
  const typed = await waitForFrame(view, (text) => text.includes("/srv/nope may not be a folder on the server"))
  expect(typed.replace(/\s*│\s*\n\s*│\s*/g, " ")).toContain("Fix Directory, or Ctrl+S retries.")
})

test("Escape keeps a launch draft, successful launch remembers settings, and discard starts empty", async () => {
  const server = fixture()
  const view = await createTestRenderer({ width: 120, height: 38 })
  cleanup.push(() => view.renderer.destroy())
  await mountDashboard(view.renderer, server.connection, server.server.url.href).ready
  view.mockInput.pressKey("n")
  await view.mockInput.typeText("Keep this task")
  view.mockInput.pressTab()
  view.mockInput.pressTab()
  await waitForFrame(view, (frame) => frame.includes("Server default") && !frame.includes("Loading agents"))
  view.mockInput.pressArrow("down")
  view.mockInput.pressTab()
  await view.mockInput.typeText("test/local")
  view.mockInput.pressEscape()
  await waitForFrame(view, (frame) => frame.includes("Draft kept"))
  view.mockInput.pressKey("n")
  await waitForFrame(view, (frame) => frame.includes("Keep this task"))
  view.mockInput.pressKey("s", { ctrl: true })
  await waitForFrame(view, (frame) => frame.includes("Task sent."))
  expect(server.posts[0]?.body).toMatchObject({ agent: "build", model: { providerID: "test", id: "local" } })
  // The launched session opens with its reply editor, so leave it before pressing n again.
  await leaveComposer(view)
  view.mockInput.pressKey("n")
  await waitForFrame(view, (frame) => frame.includes("test/local"))
  expect(view.captureCharFrame()).not.toContain("Keep this task")
  await view.mockInput.typeText("Discard this")
  view.mockInput.pressKey("F4")
  await waitForFrame(view, (frame) => frame.includes("Local draft discarded"))
  view.mockInput.pressKey("n")
  await waitForFrame(view, (frame) => frame.includes("What would you like to do?"))
  expect(view.captureCharFrame()).not.toContain("Discard this")
  expect(server.posts).toHaveLength(2)
})

test("a lost launch response survives close and reopen with the original request identity and fields", async () => {
  const server = fixture({ failPromptOnce: true })
  const view = await createTestRenderer({ width: 120, height: 38 })
  cleanup.push(() => view.renderer.destroy())
  await mountDashboard(view.renderer, server.connection, server.server.url.href).ready
  view.mockInput.pressKey("n")
  await view.mockInput.typeText("Run exactly once")
  view.mockInput.pressKey("s", { ctrl: true })
  await waitForFrame(view, (frame) => frame.includes("Ctrl+S retry"))
  await view.mockInput.typeText(" accidental edit")
  view.mockInput.pressEscape()
  await waitForFrame(view, (frame) => frame.includes("Original submission kept"))
  view.mockInput.pressKey("n")
  await waitForFrame(view, (frame) => frame.includes("Run exactly once"))
  expect(view.captureCharFrame()).not.toContain("accidental edit")
  view.mockInput.pressKey("s", { ctrl: true })
  await waitForFrame(view, (frame) => frame.includes("Task sent."))
  expect(server.posts.filter((post) => post.path === "/api/session")).toHaveLength(1)
  expect(server.posts[2]).toEqual(server.posts[1])
})

test("reopened launch retry succeeds even if unrelated agent discovery fails afterward", async () => {
  const settings: { failPromptOnce: boolean; agentStatus?: number } = { failPromptOnce: true }
  const server = fixture(settings)
  const view = await createTestRenderer({ width: 120, height: 38 })
  cleanup.push(() => view.renderer.destroy())
  await mountDashboard(view.renderer, server.connection, server.server.url.href).ready
  view.mockInput.pressKey("n")
  await view.mockInput.typeText("Retry despite agent discovery failure")
  view.mockInput.pressKey("s", { ctrl: true })
  await waitForFrame(view, (frame) => frame.includes("Ctrl+S retry"))
  view.mockInput.pressEscape()
  await waitForFrame(view, (frame) => frame.includes("Original submission kept"))

  // Simulate agent discovery failing
  settings.agentStatus = 500

  // Reopen launch draft
  view.mockInput.pressKey("n")
  await waitForFrame(view, (frame) => frame.includes("Retry despite agent discovery failure"))
  // Submit the frozen retry
  view.mockInput.pressKey("s", { ctrl: true })
  await waitForFrame(view, (frame) => frame.includes("Task sent."))
  expect(server.posts.filter((post) => post.path === "/api/session")).toHaveLength(1)
})

test("a narrow launch keeps the selected session's target and settings visible", async () => {
  const server = fixture()
  server.sessions[0] = { ...server.sessions[0]!, location: { directory: "/srv/tools" } }
  const view = await createTestRenderer({ width: 70, height: 24 })
  cleanup.push(() => view.renderer.destroy())
  await mountDashboard(view.renderer, server.connection, server.server.url.href).ready
  await leaveComposer(view)
  view.mockInput.pressKey("n")
  await view.mockInput.typeText("Inspect this directory")
  await view.renderOnce()
  expect(view.captureCharFrame()).toContain("Directory: /srv/tools")
  expect(view.captureCharFrame()).toContain("Tab: folder")
  expect(view.captureCharFrame()).not.toContain("Server default")
  expect(view.captureCharFrame()).not.toContain("Model · optional")
  expect(view.captureCharFrame()).toContain("Inspect this directory")
  expect(server.posts).toHaveLength(0)
})

test("an uncertain launch exposes its ID and can be inspected before an exact retry", async () => {
  const server = fixture({ failPromptOnce: true })
  const view = await createTestRenderer({ width: 70, height: 24 })
  cleanup.push(() => view.renderer.destroy())
  await mountDashboard(view.renderer, server.connection, server.server.url.href).ready
  await leaveComposer(view)
  view.mockInput.pressKey("n")
  await view.mockInput.typeText("Inspect before retry")
  view.mockInput.pressKey("s", { ctrl: true })
  await waitForFrame(view, (frame) => frame.includes("Ctrl+O inspect"))
  const id = server.posts[0]!.body.id as string
  expect(view.captureCharFrame()).toContain(id)
  view.mockInput.pressKey("o", { ctrl: true })
  await waitForFrame(view, (frame) => frame.includes("New agent"))
  await leaveComposer(view)
  view.mockInput.pressKey("i")
  await waitForFrame(view, (frame) => frame.includes(id))
  view.mockInput.pressEscape()
  await waitForFrame(view, (frame) => !frame.includes("SERVER"))
  expect(server.posts).toHaveLength(2)
  view.mockInput.pressKey("n")
  await waitForFrame(view, (frame) => frame.includes("Ctrl+O inspect"))
  view.mockInput.pressKey("s", { ctrl: true })
  await waitForFrame(view, (frame) => frame.includes("Task sent."))
  expect(server.posts).toHaveLength(3)
  expect(server.posts[2]).toEqual(server.posts[1])
})

test("inspection fetches the exact older session and cannot select an ID mentioned in another title", async () => {
  const server = fixture({ failPromptOnce: true, active: false })
  const view = await createTestRenderer({ width: 120, height: 38 })
  cleanup.push(() => view.renderer.destroy())
  const app = mountDashboard(view.renderer, server.connection, server.server.url.href)
  await app.ready
  view.mockInput.pressKey("n")
  await view.mockInput.typeText("Inspect the exact session")
  view.mockInput.pressKey("s", { ctrl: true })
  await waitForFrame(view, (frame) => frame.includes("Ctrl+O inspect"))
  const intended = server.sessions.shift()!
  server.historical.set(intended.id, { ...intended, title: "Intended older session" })
  server.sessions[0] = { ...server.sessions[0]!, title: `Unrelated mentions ${intended.id}` }
  view.mockInput.pressKey("o", { ctrl: true })
  await waitForFrame(view, (frame) => frame.includes("Intended older session"))
  expect(view.captureCharFrame()).not.toContain("Unrelated mentions")
  expect(server.reads).toContain(`/api/session/${intended.id}`)
  await app.refresh()
  await view.renderOnce()
  expect(view.captureCharFrame()).toContain("Intended older session")
  expect(server.posts).toHaveLength(2)
})

test("clicking Settings reveals launch controls and preserves custom choices in the collapsed draft", async () => {
  const server = fixture()
  const view = await createTestRenderer({ width: 120, height: 38 })
  cleanup.push(() => view.renderer.destroy())
  await mountDashboard(view.renderer, server.connection, server.server.url.href).ready
  view.mockInput.pressKey("n")
  await view.mockInput.typeText("A short task")
  await view.renderOnce()
  expect(view.captureCharFrame()).not.toContain("Directory on the server")
  expect(view.captureCharFrame()).not.toContain("Model · optional")
  const lines = view.captureCharFrame().split("\n")
  const y = lines.findIndex((line) => line.includes("Tab: folder"))
  await view.mockMouse.click(lines[y]!.indexOf("Tab: folder") + 1, y)
  view.mockInput.pressTab()
  await waitForFrame(view, (frame) => frame.includes("Server default") && !frame.includes("Loading agents"))
  view.mockInput.pressArrow("down")
  view.mockInput.pressTab()
  await view.mockInput.typeText("test/local")
  view.mockInput.pressEscape()
  await waitForFrame(view, (frame) => frame.includes("Draft kept"))
  view.mockInput.pressKey("n")
  // The settings stay open, so they show the choices and the summary above them is gone.
  await waitForFrame(view, (frame) => frame.includes("test/local") && frame.includes("▶ build"))
  expect(view.captureCharFrame()).not.toContain("Tab: folder")
  expect(view.captureCharFrame()).not.toContain("Model · optional")
  expect(view.captureCharFrame()).toContain("A short task")
  expect(server.posts).toHaveLength(0)
})

test("launching from mouse search opens the new session and restores keyboard shortcuts", async () => {
  const server = fixture()
  server.sessions.push({ ...server.sessions[0]!, id: "ses_second", title: "Second task" })
  const view = await createTestRenderer({ width: 120, height: 36 })
  cleanup.push(() => view.renderer.destroy())
  await mountDashboard(view.renderer, server.connection, server.server.url.href).ready
  view.mockInput.pressKey("/")
  await view.mockInput.typeText("Second")
  await waitForFrame(view, (frame) => frame.includes("Switch session"))
  const lines = view.captureCharFrame().split("\n")
  const y = lines.findIndex((line) => line.includes("+ New session  Ctrl+N"))
  await view.mockMouse.click(lines[y]!.indexOf("New session") + 1, y)
  await waitForFrame(view, (frame) => frame.includes("What would you like to do?"))
  await view.mockInput.typeText("New task from search")
  view.mockInput.pressKey("s", { ctrl: true })
  const frame = await waitForFrame(view, (frame) => frame.includes("Task sent.") && frame.includes("New agent"))
  expect(frame).toContain("New agent")
  expect(frame).not.toContain("Find: Second")
  await leaveComposer(view)
  view.mockInput.pressKey("n")
  await waitForFrame(view, (frame) => frame.includes("What would you like to do?"))
  expect(server.posts).toHaveLength(2)
  expect(server.posts[1]?.body).toMatchObject({ prompt: { text: "New task from search" } })
})
