import { createHash } from "node:crypto"
import { existsSync } from "node:fs"
import { readdir, readFile } from "node:fs/promises"
import path from "node:path"

// Verify every packages/*-wasm checksum manifest covers the checked-in files.
// These packages are generated by tools/*/script/pack*.mjs; a mismatch means a
// package was edited by hand or a manifest went stale.

const packagesDir = path.resolve(import.meta.dirname, "../packages")
const failures: string[] = []

for (const entry of await readdir(packagesDir, { withFileTypes: true })) {
  if (!entry.isDirectory() || !entry.name.endsWith("-wasm")) continue
  const dir = path.join(packagesDir, entry.name)
  if (!existsSync(path.join(dir, "package.json"))) {
    failures.push(`${entry.name}: no package.json (workspace dependency missing)`)
    continue
  }
  const manifests = (await readdir(dir)).filter((f) => f.startsWith("SHA256SUMS"))
  if (!manifests.length) {
    failures.push(`${entry.name}: no SHA256SUMS manifest`)
    continue
  }
  for (const manifest of manifests) {
    const lines = (await readFile(path.join(dir, manifest), "utf8"))
      .split("\n")
      .filter((line) => line.trim())
    for (const line of lines) {
      const [expected, file] = line.split(/\s+/, 2)
      const actual = createHash("sha256")
        .update(await readFile(path.join(dir, file!)))
        .digest("hex")
      if (actual !== expected) failures.push(`${entry.name}/${file}: checksum mismatch`)
    }
  }
}

if (failures.length) {
  console.error(failures.join("\n"))
  process.exit(1)
}
console.log("all packages/*-wasm checksums verified")
