import { afterEach, expect, test } from "bun:test"
import { createRequire } from "node:module"
import { mkdtemp, rm } from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { updateFeeds, verifyUpdateArtifacts } from "./update-artifacts"

const requireBuilder = createRequire(import.meta.resolve("electron-builder"))
const { Platform } = requireBuilder("app-builder-lib")
const { createUpdateInfoTasks, writeUpdateInfoFiles } = requireBuilder("app-builder-lib/out/publish/updateInfoBuilder")
const { Arch } = createRequire(requireBuilder.resolve("app-builder-lib"))("builder-util")
const directories: string[] = []

afterEach(async () => {
  await Promise.all(directories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })))
})

async function fixture() {
  const directory = await mkdtemp(path.join(os.tmpdir(), "turen-update-feeds-"))
  directories.push(directory)
  for (const feed of updateFeeds) {
    const arch = feed.artifact.includes("arm64") ? "arm64" : "x64"
    const packager = {
      platform: feed.artifact.includes("-mac-")
        ? Platform.MAC
        : feed.artifact.includes("-win-")
          ? Platform.WINDOWS
          : Platform.LINUX,
      appInfo: { version: "1.0.5" },
      platformSpecificBuildOptions: {},
      config: { releaseInfo: { releaseNotes: "Test update" } },
      info: { metadata: { dependencies: { "electron-updater": "6.8.9" } } },
    }
    const artifacts = feed.artifact.endsWith(".AppImage")
      ? ["AppImage", "deb", "rpm"].map((extension) => feed.artifact.replace(/AppImage$/, extension))
      : [feed.artifact]
    const tasks = await Promise.all(
      artifacts.map(async (artifact) => {
        const file = path.join(directory, artifact)
        const size = await Bun.write(file, `Test artifact ${artifact}`)
        return createUpdateInfoTasks(
          { file, arch: Arch[arch], target: { outDir: directory }, packager, updateInfo: { size } },
          [{ provider: "github", owner: "turenlabs", repo: "turenos", channel: `latest-${arch}` }],
        )
      }),
    )
    await writeUpdateInfoFiles(tasks.flat(), { emitArtifactCreated: async () => {} })
    if (feed.blockmap) await Bun.write(path.join(directory, `${feed.artifact}.blockmap`), "test blockmap")
  }
  return directory
}

test("verifies all six feeds generated by the installed Electron builder", async () => {
  const directory = await fixture()
  await verifyUpdateArtifacts(directory, "1.0.5")
  expect(await Array.fromAsync(new Bun.Glob("*.yml").scan(directory))).toHaveLength(6)
})

test("rejects missing feeds and required blockmaps", async () => {
  const directory = await fixture()
  await rm(path.join(directory, `${updateFeeds[0].artifact}.blockmap`))
  await expect(verifyUpdateArtifacts(directory, "1.0.5")).rejects.toThrow("missing blockmap")
  await rm(path.join(directory, updateFeeds[0].name))
  await expect(verifyUpdateArtifacts(directory, "1.0.5")).rejects.toThrow()
})

test("rejects incorrect release versions and modified artifacts", async () => {
  const directory = await fixture()
  await expect(verifyUpdateArtifacts(directory, "1.0.6")).rejects.toThrow("expected version 1.0.6")
  const file = Bun.file(path.join(directory, updateFeeds[0].artifact))
  await Bun.write(file, "x".repeat(file.size))
  await expect(verifyUpdateArtifacts(directory, "1.0.5")).rejects.toThrow("checksum mismatch")
})

test.each(["../outside.zip", "https://example.com/app.zip", "turenos-desktop-mac-arm64.zip"])(
  "rejects unexpected feed asset %s",
  async (url) => {
    const directory = await fixture()
    const file = Bun.file(path.join(directory, updateFeeds[0].name))
    await Bun.write(
      file,
      (await file.text()).replace("files:\n", `files:\n  - url: ${JSON.stringify(url)}\n    sha512: invalid\n`),
    )
    await expect(verifyUpdateArtifacts(directory, "1.0.5")).rejects.toThrow("invalid asset")
  },
)
