// Generated by @turenlabs/httpapi-codegen. Do not edit.
import { Effect, Stream, Schema } from "effect"
import { Sse } from "effect/unstable/encoding"
import { HttpClientError } from "effect/unstable/http"
import { HttpApiClient } from "effect/unstable/httpapi"
import { ClientApi } from "../contract"
import { ClientError } from "./client-error"

type RawClient = HttpApiClient.ForApi<typeof ClientApi>

const mapClientError = <E>(error: E) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : error

const Endpoint0_0 = (raw: RawClient["server.health"]) => () =>
  raw["health.get"]({}).pipe(Effect.mapError(mapClientError))

const adaptGroup0 = (raw: RawClient["server.health"]) => ({ get: Endpoint0_0(raw) })

type Endpoint1_0Request = Parameters<RawClient["server.location"]["location.get"]>[0]
type Endpoint1_0Input = { readonly location?: Endpoint1_0Request["query"]["location"] }
const Endpoint1_0 = (raw: RawClient["server.location"]) => (input?: Endpoint1_0Input) =>
  raw["location.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup1 = (raw: RawClient["server.location"]) => ({ get: Endpoint1_0(raw) })

type Endpoint2_0Request = Parameters<RawClient["server.agent"]["agent.list"]>[0]
type Endpoint2_0Input = { readonly location?: Endpoint2_0Request["query"]["location"] }
const Endpoint2_0 = (raw: RawClient["server.agent"]) => (input?: Endpoint2_0Input) =>
  raw["agent.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup2 = (raw: RawClient["server.agent"]) => ({ list: Endpoint2_0(raw) })

type Endpoint3_0Request = Parameters<RawClient["server.session"]["session.list"]>[0]
type Endpoint3_0Input = {
  readonly workspace?: Endpoint3_0Request["query"]["workspace"]
  readonly roots?: Endpoint3_0Request["query"]["roots"]
  readonly archived?: Endpoint3_0Request["query"]["archived"]
  readonly internal?: Endpoint3_0Request["query"]["internal"]
  readonly inactive?: Endpoint3_0Request["query"]["inactive"]
  readonly limit?: Endpoint3_0Request["query"]["limit"]
  readonly order?: Endpoint3_0Request["query"]["order"]
  readonly search?: Endpoint3_0Request["query"]["search"]
  readonly directory?: Endpoint3_0Request["query"]["directory"]
  readonly project?: Endpoint3_0Request["query"]["project"]
  readonly subpath?: Endpoint3_0Request["query"]["subpath"]
  readonly cursor?: Endpoint3_0Request["query"]["cursor"]
}
const Endpoint3_0 = (raw: RawClient["server.session"]) => (input?: Endpoint3_0Input) =>
  raw["session.list"]({
    query: {
      workspace: input?.["workspace"],
      roots: input?.["roots"],
      archived: input?.["archived"],
      internal: input?.["internal"],
      inactive: input?.["inactive"],
      limit: input?.["limit"],
      order: input?.["order"],
      search: input?.["search"],
      directory: input?.["directory"],
      project: input?.["project"],
      subpath: input?.["subpath"],
      cursor: input?.["cursor"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_1Request = Parameters<RawClient["server.session"]["session.create"]>[0]
type Endpoint3_1Input = {
  readonly id?: Endpoint3_1Request["payload"]["id"]
  readonly agent?: Endpoint3_1Request["payload"]["agent"]
  readonly model?: Endpoint3_1Request["payload"]["model"]
  readonly metadata?: Endpoint3_1Request["payload"]["metadata"]
  readonly location?: Endpoint3_1Request["payload"]["location"]
}
const Endpoint3_1 = (raw: RawClient["server.session"]) => (input?: Endpoint3_1Input) =>
  raw["session.create"]({
    payload: {
      id: input?.["id"],
      agent: input?.["agent"],
      model: input?.["model"],
      metadata: input?.["metadata"],
      location: input?.["location"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_2Request = Parameters<RawClient["server.session"]["session.replay"]>[0]
type Endpoint3_2Input = {
  readonly query?: Endpoint3_2Request["query"]["query"]
  readonly limit?: Endpoint3_2Request["query"]["limit"]
  readonly cursor?: Endpoint3_2Request["query"]["cursor"]
}
const Endpoint3_2 = (raw: RawClient["server.session"]) => (input?: Endpoint3_2Input) =>
  raw["session.replay"]({
    query: { query: input?.["query"], limit: input?.["limit"], cursor: input?.["cursor"] },
  }).pipe(Effect.mapError(mapClientError))

const Endpoint3_3 = (raw: RawClient["server.session"]) => () =>
  raw["session.active"]({}).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const Endpoint3_4 = (raw: RawClient["server.session"]) => () =>
  raw["session.interruptAll"]({}).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_5Request = Parameters<RawClient["server.session"]["session.get"]>[0]
type Endpoint3_5Input = { readonly sessionID: Endpoint3_5Request["params"]["sessionID"] }
const Endpoint3_5 = (raw: RawClient["server.session"]) => (input: Endpoint3_5Input) =>
  raw["session.get"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_6Request = Parameters<RawClient["server.session"]["session.terminal.get"]>[0]
type Endpoint3_6Input = { readonly sessionID: Endpoint3_6Request["params"]["sessionID"] }
const Endpoint3_6 = (raw: RawClient["server.session"]) => (input: Endpoint3_6Input) =>
  raw["session.terminal.get"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_7Request = Parameters<RawClient["server.session"]["session.terminal.create"]>[0]
type Endpoint3_7Input = { readonly sessionID: Endpoint3_7Request["params"]["sessionID"] }
const Endpoint3_7 = (raw: RawClient["server.session"]) => (input: Endpoint3_7Input) =>
  raw["session.terminal.create"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_8Request = Parameters<RawClient["server.session"]["session.terminal.share"]>[0]
type Endpoint3_8Input = {
  readonly sessionID: Endpoint3_8Request["params"]["sessionID"]
  readonly shared: Endpoint3_8Request["payload"]["shared"]
}
const Endpoint3_8 = (raw: RawClient["server.session"]) => (input: Endpoint3_8Input) =>
  raw["session.terminal.share"]({
    params: { sessionID: input["sessionID"] },
    payload: { shared: input["shared"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_9Request = Parameters<RawClient["server.session"]["session.terminal.remove"]>[0]
type Endpoint3_9Input = { readonly sessionID: Endpoint3_9Request["params"]["sessionID"] }
const Endpoint3_9 = (raw: RawClient["server.session"]) => (input: Endpoint3_9Input) =>
  raw["session.terminal.remove"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_10Request = Parameters<RawClient["server.session"]["session.harness.state"]>[0]
type Endpoint3_10Input = { readonly sessionID: Endpoint3_10Request["params"]["sessionID"] }
const Endpoint3_10 = (raw: RawClient["server.session"]) => (input: Endpoint3_10Input) =>
  raw["session.harness.state"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_11Request = Parameters<RawClient["server.session"]["session.harness.proposal"]>[0]
type Endpoint3_11Input = {
  readonly sessionID: Endpoint3_11Request["params"]["sessionID"]
  readonly id?: Endpoint3_11Request["payload"]["id"]
  readonly baseVersion: Endpoint3_11Request["payload"]["baseVersion"]
  readonly summary: Endpoint3_11Request["payload"]["summary"]
  readonly changes?: Endpoint3_11Request["payload"]["changes"]
  readonly tools?: Endpoint3_11Request["payload"]["tools"]
  readonly guidance?: Endpoint3_11Request["payload"]["guidance"]
}
const Endpoint3_11 = (raw: RawClient["server.session"]) => (input: Endpoint3_11Input) =>
  raw["session.harness.proposal"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      baseVersion: input["baseVersion"],
      summary: input["summary"],
      changes: input["changes"],
      tools: input["tools"],
      guidance: input["guidance"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_12Request = Parameters<RawClient["server.session"]["session.harness.proposalStatus"]>[0]
type Endpoint3_12Input = {
  readonly sessionID: Endpoint3_12Request["params"]["sessionID"]
  readonly proposalID: Endpoint3_12Request["params"]["proposalID"]
  readonly status: Endpoint3_12Request["payload"]["status"]
  readonly validation?: Endpoint3_12Request["payload"]["validation"]
}
const Endpoint3_12 = (raw: RawClient["server.session"]) => (input: Endpoint3_12Input) =>
  raw["session.harness.proposalStatus"]({
    params: { sessionID: input["sessionID"], proposalID: input["proposalID"] },
    payload: { status: input["status"], validation: input["validation"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_13Request = Parameters<RawClient["server.session"]["session.harness.proposalApply"]>[0]
type Endpoint3_13Input = {
  readonly sessionID: Endpoint3_13Request["params"]["sessionID"]
  readonly proposalID: Endpoint3_13Request["params"]["proposalID"]
}
const Endpoint3_13 = (raw: RawClient["server.session"]) => (input: Endpoint3_13Input) =>
  raw["session.harness.proposalApply"]({
    params: { sessionID: input["sessionID"], proposalID: input["proposalID"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_14Request = Parameters<RawClient["server.session"]["session.harness.proposalReject"]>[0]
type Endpoint3_14Input = {
  readonly sessionID: Endpoint3_14Request["params"]["sessionID"]
  readonly proposalID: Endpoint3_14Request["params"]["proposalID"]
}
const Endpoint3_14 = (raw: RawClient["server.session"]) => (input: Endpoint3_14Input) =>
  raw["session.harness.proposalReject"]({
    params: { sessionID: input["sessionID"], proposalID: input["proposalID"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_15Request = Parameters<RawClient["server.session"]["session.harness.reload"]>[0]
type Endpoint3_15Input = {
  readonly sessionID: Endpoint3_15Request["params"]["sessionID"]
  readonly baseVersion: Endpoint3_15Request["payload"]["baseVersion"]
}
const Endpoint3_15 = (raw: RawClient["server.session"]) => (input: Endpoint3_15Input) =>
  raw["session.harness.reload"]({
    params: { sessionID: input["sessionID"] },
    payload: { baseVersion: input["baseVersion"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_16Request = Parameters<RawClient["server.session"]["session.harness.rollback"]>[0]
type Endpoint3_16Input = {
  readonly sessionID: Endpoint3_16Request["params"]["sessionID"]
  readonly baseVersion: Endpoint3_16Request["payload"]["baseVersion"]
  readonly version: Endpoint3_16Request["payload"]["version"]
}
const Endpoint3_16 = (raw: RawClient["server.session"]) => (input: Endpoint3_16Input) =>
  raw["session.harness.rollback"]({
    params: { sessionID: input["sessionID"] },
    payload: { baseVersion: input["baseVersion"], version: input["version"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_17Request = Parameters<RawClient["server.session"]["session.switchAgent"]>[0]
type Endpoint3_17Input = {
  readonly sessionID: Endpoint3_17Request["params"]["sessionID"]
  readonly agent: Endpoint3_17Request["payload"]["agent"]
}
const Endpoint3_17 = (raw: RawClient["server.session"]) => (input: Endpoint3_17Input) =>
  raw["session.switchAgent"]({ params: { sessionID: input["sessionID"] }, payload: { agent: input["agent"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint3_18Request = Parameters<RawClient["server.session"]["session.switchModel"]>[0]
type Endpoint3_18Input = {
  readonly sessionID: Endpoint3_18Request["params"]["sessionID"]
  readonly model: Endpoint3_18Request["payload"]["model"]
}
const Endpoint3_18 = (raw: RawClient["server.session"]) => (input: Endpoint3_18Input) =>
  raw["session.switchModel"]({ params: { sessionID: input["sessionID"] }, payload: { model: input["model"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint3_19Request = Parameters<RawClient["server.session"]["session.prompt"]>[0]
type Endpoint3_19Input = {
  readonly sessionID: Endpoint3_19Request["params"]["sessionID"]
  readonly id?: Endpoint3_19Request["payload"]["id"]
  readonly prompt: Endpoint3_19Request["payload"]["prompt"]
  readonly delivery?: Endpoint3_19Request["payload"]["delivery"]
  readonly agent?: Endpoint3_19Request["payload"]["agent"]
  readonly model?: Endpoint3_19Request["payload"]["model"]
  readonly resume?: Endpoint3_19Request["payload"]["resume"]
}
const Endpoint3_19 = (raw: RawClient["server.session"]) => (input: Endpoint3_19Input) =>
  raw["session.prompt"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      prompt: input["prompt"],
      delivery: input["delivery"],
      agent: input["agent"],
      model: input["model"],
      resume: input["resume"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_20Request = Parameters<RawClient["server.session"]["session.shell"]>[0]
type Endpoint3_20Input = {
  readonly sessionID: Endpoint3_20Request["params"]["sessionID"]
  readonly id?: Endpoint3_20Request["payload"]["id"]
  readonly command: Endpoint3_20Request["payload"]["command"]
  readonly timeout?: Endpoint3_20Request["payload"]["timeout"]
}
const Endpoint3_20 = (raw: RawClient["server.session"]) => (input: Endpoint3_20Input) =>
  raw["session.shell"]({
    params: { sessionID: input["sessionID"] },
    payload: { id: input["id"], command: input["command"], timeout: input["timeout"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_21Request = Parameters<RawClient["server.session"]["session.command"]>[0]
type Endpoint3_21Input = {
  readonly sessionID: Endpoint3_21Request["params"]["sessionID"]
  readonly id?: Endpoint3_21Request["payload"]["id"]
  readonly command: Endpoint3_21Request["payload"]["command"]
  readonly arguments: Endpoint3_21Request["payload"]["arguments"]
  readonly agent?: Endpoint3_21Request["payload"]["agent"]
  readonly model?: Endpoint3_21Request["payload"]["model"]
  readonly files?: Endpoint3_21Request["payload"]["files"]
  readonly resume?: Endpoint3_21Request["payload"]["resume"]
}
const Endpoint3_21 = (raw: RawClient["server.session"]) => (input: Endpoint3_21Input) =>
  raw["session.command"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      command: input["command"],
      arguments: input["arguments"],
      agent: input["agent"],
      model: input["model"],
      files: input["files"],
      resume: input["resume"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_22Request = Parameters<RawClient["server.session"]["session.resume"]>[0]
type Endpoint3_22Input = { readonly sessionID: Endpoint3_22Request["params"]["sessionID"] }
const Endpoint3_22 = (raw: RawClient["server.session"]) => (input: Endpoint3_22Input) =>
  raw["session.resume"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_23Request = Parameters<RawClient["server.session"]["session.goalGet"]>[0]
type Endpoint3_23Input = { readonly sessionID: Endpoint3_23Request["params"]["sessionID"] }
const Endpoint3_23 = (raw: RawClient["server.session"]) => (input: Endpoint3_23Input) =>
  raw["session.goalGet"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_24Request = Parameters<RawClient["server.session"]["session.goalSet"]>[0]
type Endpoint3_24Input = {
  readonly sessionID: Endpoint3_24Request["params"]["sessionID"]
  readonly id?: Endpoint3_24Request["payload"]["id"]
  readonly messageID?: Endpoint3_24Request["payload"]["messageID"]
  readonly objective: Endpoint3_24Request["payload"]["objective"]
  readonly agent?: Endpoint3_24Request["payload"]["agent"]
  readonly model?: Endpoint3_24Request["payload"]["model"]
}
const Endpoint3_24 = (raw: RawClient["server.session"]) => (input: Endpoint3_24Input) =>
  raw["session.goalSet"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      messageID: input["messageID"],
      objective: input["objective"],
      agent: input["agent"],
      model: input["model"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_25Request = Parameters<RawClient["server.session"]["session.goalEdit"]>[0]
type Endpoint3_25Input = {
  readonly sessionID: Endpoint3_25Request["params"]["sessionID"]
  readonly goalID: Endpoint3_25Request["payload"]["goalID"]
  readonly expectedRevision: Endpoint3_25Request["payload"]["expectedRevision"]
  readonly objective: Endpoint3_25Request["payload"]["objective"]
}
const Endpoint3_25 = (raw: RawClient["server.session"]) => (input: Endpoint3_25Input) =>
  raw["session.goalEdit"]({
    params: { sessionID: input["sessionID"] },
    payload: { goalID: input["goalID"], expectedRevision: input["expectedRevision"], objective: input["objective"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_26Request = Parameters<RawClient["server.session"]["session.goalStatus"]>[0]
type Endpoint3_26Input = {
  readonly sessionID: Endpoint3_26Request["params"]["sessionID"]
  readonly goalID: Endpoint3_26Request["payload"]["goalID"]
  readonly expectedRevision: Endpoint3_26Request["payload"]["expectedRevision"]
  readonly status: Endpoint3_26Request["payload"]["status"]
}
const Endpoint3_26 = (raw: RawClient["server.session"]) => (input: Endpoint3_26Input) =>
  raw["session.goalStatus"]({
    params: { sessionID: input["sessionID"] },
    payload: { goalID: input["goalID"], expectedRevision: input["expectedRevision"], status: input["status"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_27Request = Parameters<RawClient["server.session"]["session.goalClear"]>[0]
type Endpoint3_27Input = {
  readonly sessionID: Endpoint3_27Request["params"]["sessionID"]
  readonly goalID: Endpoint3_27Request["payload"]["goalID"]
  readonly expectedRevision: Endpoint3_27Request["payload"]["expectedRevision"]
}
const Endpoint3_27 = (raw: RawClient["server.session"]) => (input: Endpoint3_27Input) =>
  raw["session.goalClear"]({
    params: { sessionID: input["sessionID"] },
    payload: { goalID: input["goalID"], expectedRevision: input["expectedRevision"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_28Request = Parameters<RawClient["server.session"]["session.taskList"]>[0]
type Endpoint3_28Input = {
  readonly sessionID: Endpoint3_28Request["params"]["sessionID"]
  readonly limit?: Endpoint3_28Request["query"]["limit"]
  readonly cursor?: Endpoint3_28Request["query"]["cursor"]
}
const Endpoint3_28 = (raw: RawClient["server.session"]) => (input: Endpoint3_28Input) =>
  raw["session.taskList"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], cursor: input["cursor"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_29Request = Parameters<RawClient["server.session"]["session.taskGet"]>[0]
type Endpoint3_29Input = {
  readonly sessionID: Endpoint3_29Request["params"]["sessionID"]
  readonly taskID: Endpoint3_29Request["params"]["taskID"]
}
const Endpoint3_29 = (raw: RawClient["server.session"]) => (input: Endpoint3_29Input) =>
  raw["session.taskGet"]({ params: { sessionID: input["sessionID"], taskID: input["taskID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_30Request = Parameters<RawClient["server.session"]["session.taskCancel"]>[0]
type Endpoint3_30Input = {
  readonly sessionID: Endpoint3_30Request["params"]["sessionID"]
  readonly taskID: Endpoint3_30Request["params"]["taskID"]
  readonly expectedRevision?: Endpoint3_30Request["payload"]["expectedRevision"]
}
const Endpoint3_30 = (raw: RawClient["server.session"]) => (input: Endpoint3_30Input) =>
  raw["session.taskCancel"]({
    params: { sessionID: input["sessionID"], taskID: input["taskID"] },
    payload: { expectedRevision: input["expectedRevision"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_31Request = Parameters<RawClient["server.session"]["session.teamBoard"]>[0]
type Endpoint3_31Input = { readonly sessionID: Endpoint3_31Request["params"]["sessionID"] }
const Endpoint3_31 = (raw: RawClient["server.session"]) => (input: Endpoint3_31Input) =>
  raw["session.teamBoard"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_32Request = Parameters<RawClient["server.session"]["session.swarmRoom"]>[0]
type Endpoint3_32Input = { readonly sessionID: Endpoint3_32Request["params"]["sessionID"] }
const Endpoint3_32 = (raw: RawClient["server.session"]) => (input: Endpoint3_32Input) =>
  raw["session.swarmRoom"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_33Request = Parameters<RawClient["server.session"]["session.swarmRoomEntries"]>[0]
type Endpoint3_33Input = {
  readonly sessionID: Endpoint3_33Request["params"]["sessionID"]
  readonly after?: Endpoint3_33Request["query"]["after"]
  readonly limit?: Endpoint3_33Request["query"]["limit"]
}
const Endpoint3_33 = (raw: RawClient["server.session"]) => (input: Endpoint3_33Input) =>
  raw["session.swarmRoomEntries"]({
    params: { sessionID: input["sessionID"] },
    query: { after: input["after"], limit: input["limit"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_34Request = Parameters<RawClient["server.session"]["session.swarmRoomPost"]>[0]
type Endpoint3_34Input = {
  readonly sessionID: Endpoint3_34Request["params"]["sessionID"]
  readonly text: Endpoint3_34Request["payload"]["text"]
  readonly name?: Endpoint3_34Request["payload"]["name"]
  readonly replyTo?: Endpoint3_34Request["payload"]["replyTo"]
}
const Endpoint3_34 = (raw: RawClient["server.session"]) => (input: Endpoint3_34Input) =>
  raw["session.swarmRoomPost"]({
    params: { sessionID: input["sessionID"] },
    payload: { text: input["text"], name: input["name"], replyTo: input["replyTo"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_35Request = Parameters<RawClient["server.session"]["session.compact"]>[0]
type Endpoint3_35Input = { readonly sessionID: Endpoint3_35Request["params"]["sessionID"] }
const Endpoint3_35 = (raw: RawClient["server.session"]) => (input: Endpoint3_35Input) =>
  raw["session.compact"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_36Request = Parameters<RawClient["server.session"]["session.wait"]>[0]
type Endpoint3_36Input = { readonly sessionID: Endpoint3_36Request["params"]["sessionID"] }
const Endpoint3_36 = (raw: RawClient["server.session"]) => (input: Endpoint3_36Input) =>
  raw["session.wait"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_37Request = Parameters<RawClient["server.session"]["session.revert.stage"]>[0]
type Endpoint3_37Input = {
  readonly sessionID: Endpoint3_37Request["params"]["sessionID"]
  readonly messageID: Endpoint3_37Request["payload"]["messageID"]
  readonly files?: Endpoint3_37Request["payload"]["files"]
}
const Endpoint3_37 = (raw: RawClient["server.session"]) => (input: Endpoint3_37Input) =>
  raw["session.revert.stage"]({
    params: { sessionID: input["sessionID"] },
    payload: { messageID: input["messageID"], files: input["files"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_38Request = Parameters<RawClient["server.session"]["session.revert.clear"]>[0]
type Endpoint3_38Input = { readonly sessionID: Endpoint3_38Request["params"]["sessionID"] }
const Endpoint3_38 = (raw: RawClient["server.session"]) => (input: Endpoint3_38Input) =>
  raw["session.revert.clear"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_39Request = Parameters<RawClient["server.session"]["session.revert.commit"]>[0]
type Endpoint3_39Input = { readonly sessionID: Endpoint3_39Request["params"]["sessionID"] }
const Endpoint3_39 = (raw: RawClient["server.session"]) => (input: Endpoint3_39Input) =>
  raw["session.revert.commit"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_40Request = Parameters<RawClient["server.session"]["session.context"]>[0]
type Endpoint3_40Input = { readonly sessionID: Endpoint3_40Request["params"]["sessionID"] }
const Endpoint3_40 = (raw: RawClient["server.session"]) => (input: Endpoint3_40Input) =>
  raw["session.context"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_41Request = Parameters<RawClient["server.session"]["session.pendingInputs"]>[0]
type Endpoint3_41Input = { readonly sessionID: Endpoint3_41Request["params"]["sessionID"] }
const Endpoint3_41 = (raw: RawClient["server.session"]) => (input: Endpoint3_41Input) =>
  raw["session.pendingInputs"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_42Request = Parameters<RawClient["server.session"]["session.inputStatus"]>[0]
type Endpoint3_42Input = {
  readonly sessionID: Endpoint3_42Request["params"]["sessionID"]
  readonly messageID: Endpoint3_42Request["params"]["messageID"]
}
const Endpoint3_42 = (raw: RawClient["server.session"]) => (input: Endpoint3_42Input) =>
  raw["session.inputStatus"]({ params: { sessionID: input["sessionID"], messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_43Request = Parameters<RawClient["server.session"]["session.outbox"]>[0]
type Endpoint3_43Input = {
  readonly sessionID: Endpoint3_43Request["params"]["sessionID"]
  readonly limit?: Endpoint3_43Request["query"]["limit"]
  readonly cursor?: Endpoint3_43Request["query"]["cursor"]
  readonly status?: Endpoint3_43Request["query"]["status"]
}
const Endpoint3_43 = (raw: RawClient["server.session"]) => (input: Endpoint3_43Input) =>
  raw["session.outbox"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], cursor: input["cursor"], status: input["status"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_44Request = Parameters<RawClient["server.session"]["session.history"]>[0]
type Endpoint3_44Input = {
  readonly sessionID: Endpoint3_44Request["params"]["sessionID"]
  readonly limit?: Endpoint3_44Request["query"]["limit"]
  readonly after?: Endpoint3_44Request["query"]["after"]
}
const Endpoint3_44 = (raw: RawClient["server.session"]) => (input: Endpoint3_44Input) =>
  raw["session.history"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], after: input["after"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_45Request = Parameters<RawClient["server.session"]["session.replayHistory"]>[0]
type Endpoint3_45Input = {
  readonly sessionID: Endpoint3_45Request["params"]["sessionID"]
  readonly limit?: Endpoint3_45Request["query"]["limit"]
  readonly cursor?: Endpoint3_45Request["query"]["cursor"]
  readonly anchor?: Endpoint3_45Request["query"]["anchor"]
  readonly direction?: Endpoint3_45Request["query"]["direction"]
}
const Endpoint3_45 = (raw: RawClient["server.session"]) => (input: Endpoint3_45Input) =>
  raw["session.replayHistory"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], cursor: input["cursor"], anchor: input["anchor"], direction: input["direction"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_46Request = Parameters<RawClient["server.session"]["session.events"]>[0]
type Endpoint3_46Input = {
  readonly sessionID: Endpoint3_46Request["params"]["sessionID"]
  readonly after?: Endpoint3_46Request["query"]["after"]
}
const Endpoint3_46 = (raw: RawClient["server.session"]) => (input: Endpoint3_46Input) =>
  Stream.unwrap(
    raw["session.events"]({ params: { sessionID: input["sessionID"] }, query: { after: input["after"] } }).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

type Endpoint3_47Request = Parameters<RawClient["server.session"]["session.interrupt"]>[0]
type Endpoint3_47Input = { readonly sessionID: Endpoint3_47Request["params"]["sessionID"] }
const Endpoint3_47 = (raw: RawClient["server.session"]) => (input: Endpoint3_47Input) =>
  raw["session.interrupt"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_48Request = Parameters<RawClient["server.session"]["session.message"]>[0]
type Endpoint3_48Input = {
  readonly sessionID: Endpoint3_48Request["params"]["sessionID"]
  readonly messageID: Endpoint3_48Request["params"]["messageID"]
}
const Endpoint3_48 = (raw: RawClient["server.session"]) => (input: Endpoint3_48Input) =>
  raw["session.message"]({ params: { sessionID: input["sessionID"], messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const adaptGroup3 = (raw: RawClient["server.session"]) => ({
  list: Endpoint3_0(raw),
  create: Endpoint3_1(raw),
  replay: Endpoint3_2(raw),
  active: Endpoint3_3(raw),
  interruptAll: Endpoint3_4(raw),
  get: Endpoint3_5(raw),
  getTerminal: Endpoint3_6(raw),
  createTerminal: Endpoint3_7(raw),
  shareTerminal: Endpoint3_8(raw),
  removeTerminal: Endpoint3_9(raw),
  state: Endpoint3_10(raw),
  proposal: Endpoint3_11(raw),
  proposalStatus: Endpoint3_12(raw),
  proposalApply: Endpoint3_13(raw),
  proposalReject: Endpoint3_14(raw),
  reload: Endpoint3_15(raw),
  rollback: Endpoint3_16(raw),
  switchAgent: Endpoint3_17(raw),
  switchModel: Endpoint3_18(raw),
  prompt: Endpoint3_19(raw),
  shell: Endpoint3_20(raw),
  command: Endpoint3_21(raw),
  resume: Endpoint3_22(raw),
  goalGet: Endpoint3_23(raw),
  goalSet: Endpoint3_24(raw),
  goalEdit: Endpoint3_25(raw),
  goalStatus: Endpoint3_26(raw),
  goalClear: Endpoint3_27(raw),
  taskList: Endpoint3_28(raw),
  taskGet: Endpoint3_29(raw),
  taskCancel: Endpoint3_30(raw),
  teamBoard: Endpoint3_31(raw),
  swarmRoom: Endpoint3_32(raw),
  swarmRoomEntries: Endpoint3_33(raw),
  swarmRoomPost: Endpoint3_34(raw),
  compact: Endpoint3_35(raw),
  wait: Endpoint3_36(raw),
  stage: Endpoint3_37(raw),
  clear: Endpoint3_38(raw),
  commit: Endpoint3_39(raw),
  context: Endpoint3_40(raw),
  pendingInputs: Endpoint3_41(raw),
  inputStatus: Endpoint3_42(raw),
  outbox: Endpoint3_43(raw),
  history: Endpoint3_44(raw),
  replayHistory: Endpoint3_45(raw),
  events: Endpoint3_46(raw),
  interrupt: Endpoint3_47(raw),
  message: Endpoint3_48(raw),
})

type Endpoint4_0Request = Parameters<RawClient["server.message"]["session.messages"]>[0]
type Endpoint4_0Input = {
  readonly sessionID: Endpoint4_0Request["params"]["sessionID"]
  readonly limit?: Endpoint4_0Request["query"]["limit"]
  readonly order?: Endpoint4_0Request["query"]["order"]
  readonly cursor?: Endpoint4_0Request["query"]["cursor"]
  readonly lean?: Endpoint4_0Request["query"]["lean"]
}
const Endpoint4_0 = (raw: RawClient["server.message"]) => (input: Endpoint4_0Input) =>
  raw["session.messages"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], order: input["order"], cursor: input["cursor"], lean: input["lean"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup4 = (raw: RawClient["server.message"]) => ({ list: Endpoint4_0(raw) })

type Endpoint5_0Request = Parameters<RawClient["server.permission"]["permission.request.list"]>[0]
type Endpoint5_0Input = { readonly location?: Endpoint5_0Request["query"]["location"] }
const Endpoint5_0 = (raw: RawClient["server.permission"]) => (input?: Endpoint5_0Input) =>
  raw["permission.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint5_1Request = Parameters<RawClient["server.permission"]["permission.saved.list"]>[0]
type Endpoint5_1Input = { readonly projectID?: Endpoint5_1Request["query"]["projectID"] }
const Endpoint5_1 = (raw: RawClient["server.permission"]) => (input?: Endpoint5_1Input) =>
  raw["permission.saved.list"]({ query: { projectID: input?.["projectID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint5_2Request = Parameters<RawClient["server.permission"]["permission.saved.remove"]>[0]
type Endpoint5_2Input = { readonly id: Endpoint5_2Request["params"]["id"] }
const Endpoint5_2 = (raw: RawClient["server.permission"]) => (input: Endpoint5_2Input) =>
  raw["permission.saved.remove"]({ params: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint5_3Request = Parameters<RawClient["server.permission"]["session.permission.create"]>[0]
type Endpoint5_3Input = {
  readonly sessionID: Endpoint5_3Request["params"]["sessionID"]
  readonly id?: Endpoint5_3Request["payload"]["id"]
  readonly action: Endpoint5_3Request["payload"]["action"]
  readonly resources: Endpoint5_3Request["payload"]["resources"]
  readonly save?: Endpoint5_3Request["payload"]["save"]
  readonly metadata?: Endpoint5_3Request["payload"]["metadata"]
  readonly source?: Endpoint5_3Request["payload"]["source"]
  readonly agent?: Endpoint5_3Request["payload"]["agent"]
}
const Endpoint5_3 = (raw: RawClient["server.permission"]) => (input: Endpoint5_3Input) =>
  raw["session.permission.create"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      action: input["action"],
      resources: input["resources"],
      save: input["save"],
      metadata: input["metadata"],
      source: input["source"],
      agent: input["agent"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint5_4Request = Parameters<RawClient["server.permission"]["session.permission.list"]>[0]
type Endpoint5_4Input = { readonly sessionID: Endpoint5_4Request["params"]["sessionID"] }
const Endpoint5_4 = (raw: RawClient["server.permission"]) => (input: Endpoint5_4Input) =>
  raw["session.permission.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint5_5Request = Parameters<RawClient["server.permission"]["session.permission.get"]>[0]
type Endpoint5_5Input = {
  readonly sessionID: Endpoint5_5Request["params"]["sessionID"]
  readonly requestID: Endpoint5_5Request["params"]["requestID"]
}
const Endpoint5_5 = (raw: RawClient["server.permission"]) => (input: Endpoint5_5Input) =>
  raw["session.permission.get"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint5_6Request = Parameters<RawClient["server.permission"]["session.permission.reply"]>[0]
type Endpoint5_6Input = {
  readonly sessionID: Endpoint5_6Request["params"]["sessionID"]
  readonly requestID: Endpoint5_6Request["params"]["requestID"]
  readonly reply: Endpoint5_6Request["payload"]["reply"]
  readonly message?: Endpoint5_6Request["payload"]["message"]
}
const Endpoint5_6 = (raw: RawClient["server.permission"]) => (input: Endpoint5_6Input) =>
  raw["session.permission.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { reply: input["reply"], message: input["message"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup5 = (raw: RawClient["server.permission"]) => ({
  listRequests: Endpoint5_0(raw),
  listSaved: Endpoint5_1(raw),
  removeSaved: Endpoint5_2(raw),
  create: Endpoint5_3(raw),
  list: Endpoint5_4(raw),
  get: Endpoint5_5(raw),
  reply: Endpoint5_6(raw),
})

type Endpoint6_0Request = Parameters<RawClient["server.fs"]["fs.list"]>[0]
type Endpoint6_0Input = {
  readonly location?: Endpoint6_0Request["query"]["location"]
  readonly path?: Endpoint6_0Request["query"]["path"]
}
const Endpoint6_0 = (raw: RawClient["server.fs"]) => (input?: Endpoint6_0Input) =>
  raw["fs.list"]({ query: { location: input?.["location"], path: input?.["path"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint6_1Request = Parameters<RawClient["server.fs"]["fs.find"]>[0]
type Endpoint6_1Input = {
  readonly location?: Endpoint6_1Request["query"]["location"]
  readonly query: Endpoint6_1Request["query"]["query"]
  readonly type?: Endpoint6_1Request["query"]["type"]
  readonly limit?: Endpoint6_1Request["query"]["limit"]
}
const Endpoint6_1 = (raw: RawClient["server.fs"]) => (input: Endpoint6_1Input) =>
  raw["fs.find"]({
    query: { location: input["location"], query: input["query"], type: input["type"], limit: input["limit"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup6 = (raw: RawClient["server.fs"]) => ({ list: Endpoint6_0(raw), find: Endpoint6_1(raw) })

type Endpoint7_0Request = Parameters<RawClient["server.command"]["command.list"]>[0]
type Endpoint7_0Input = { readonly location?: Endpoint7_0Request["query"]["location"] }
const Endpoint7_0 = (raw: RawClient["server.command"]) => (input?: Endpoint7_0Input) =>
  raw["command.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup7 = (raw: RawClient["server.command"]) => ({ list: Endpoint7_0(raw) })

const Endpoint8_0 = (raw: RawClient["server.event"]) => () =>
  Stream.unwrap(
    raw["event.subscribe"]({}).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

const adaptGroup8 = (raw: RawClient["server.event"]) => ({ subscribe: Endpoint8_0(raw) })

type Endpoint9_0Request = Parameters<RawClient["server.pty"]["pty.list"]>[0]
type Endpoint9_0Input = { readonly location?: Endpoint9_0Request["query"]["location"] }
const Endpoint9_0 = (raw: RawClient["server.pty"]) => (input?: Endpoint9_0Input) =>
  raw["pty.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint9_1Request = Parameters<RawClient["server.pty"]["pty.create"]>[0]
type Endpoint9_1Input = {
  readonly location?: Endpoint9_1Request["query"]["location"]
  readonly command?: Endpoint9_1Request["payload"]["command"]
  readonly args?: Endpoint9_1Request["payload"]["args"]
  readonly cwd?: Endpoint9_1Request["payload"]["cwd"]
  readonly title?: Endpoint9_1Request["payload"]["title"]
  readonly env?: Endpoint9_1Request["payload"]["env"]
}
const Endpoint9_1 = (raw: RawClient["server.pty"]) => (input?: Endpoint9_1Input) =>
  raw["pty.create"]({
    query: { location: input?.["location"] },
    payload: {
      command: input?.["command"],
      args: input?.["args"],
      cwd: input?.["cwd"],
      title: input?.["title"],
      env: input?.["env"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint9_2Request = Parameters<RawClient["server.pty"]["pty.get"]>[0]
type Endpoint9_2Input = {
  readonly ptyID: Endpoint9_2Request["params"]["ptyID"]
  readonly location?: Endpoint9_2Request["query"]["location"]
}
const Endpoint9_2 = (raw: RawClient["server.pty"]) => (input: Endpoint9_2Input) =>
  raw["pty.get"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint9_3Request = Parameters<RawClient["server.pty"]["pty.update"]>[0]
type Endpoint9_3Input = {
  readonly ptyID: Endpoint9_3Request["params"]["ptyID"]
  readonly location?: Endpoint9_3Request["query"]["location"]
  readonly title?: Endpoint9_3Request["payload"]["title"]
  readonly size?: Endpoint9_3Request["payload"]["size"]
}
const Endpoint9_3 = (raw: RawClient["server.pty"]) => (input: Endpoint9_3Input) =>
  raw["pty.update"]({
    params: { ptyID: input["ptyID"] },
    query: { location: input["location"] },
    payload: { title: input["title"], size: input["size"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint9_4Request = Parameters<RawClient["server.pty"]["pty.remove"]>[0]
type Endpoint9_4Input = {
  readonly ptyID: Endpoint9_4Request["params"]["ptyID"]
  readonly location?: Endpoint9_4Request["query"]["location"]
}
const Endpoint9_4 = (raw: RawClient["server.pty"]) => (input: Endpoint9_4Input) =>
  raw["pty.remove"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup9 = (raw: RawClient["server.pty"]) => ({
  list: Endpoint9_0(raw),
  create: Endpoint9_1(raw),
  get: Endpoint9_2(raw),
  update: Endpoint9_3(raw),
  remove: Endpoint9_4(raw),
})

type Endpoint10_0Request = Parameters<RawClient["server.question"]["question.request.list"]>[0]
type Endpoint10_0Input = { readonly location?: Endpoint10_0Request["query"]["location"] }
const Endpoint10_0 = (raw: RawClient["server.question"]) => (input?: Endpoint10_0Input) =>
  raw["question.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint10_1Request = Parameters<RawClient["server.question"]["session.question.list"]>[0]
type Endpoint10_1Input = { readonly sessionID: Endpoint10_1Request["params"]["sessionID"] }
const Endpoint10_1 = (raw: RawClient["server.question"]) => (input: Endpoint10_1Input) =>
  raw["session.question.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint10_2Request = Parameters<RawClient["server.question"]["session.question.reply"]>[0]
type Endpoint10_2Input = {
  readonly sessionID: Endpoint10_2Request["params"]["sessionID"]
  readonly requestID: Endpoint10_2Request["params"]["requestID"]
  readonly answers: Endpoint10_2Request["payload"]["answers"]
}
const Endpoint10_2 = (raw: RawClient["server.question"]) => (input: Endpoint10_2Input) =>
  raw["session.question.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { answers: input["answers"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint10_3Request = Parameters<RawClient["server.question"]["session.question.reject"]>[0]
type Endpoint10_3Input = {
  readonly sessionID: Endpoint10_3Request["params"]["sessionID"]
  readonly requestID: Endpoint10_3Request["params"]["requestID"]
}
const Endpoint10_3 = (raw: RawClient["server.question"]) => (input: Endpoint10_3Input) =>
  raw["session.question.reject"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup10 = (raw: RawClient["server.question"]) => ({
  listRequests: Endpoint10_0(raw),
  list: Endpoint10_1(raw),
  reply: Endpoint10_2(raw),
  reject: Endpoint10_3(raw),
})

type Endpoint11_0Request = Parameters<RawClient["server.projectCopy"]["projectCopy.create"]>[0]
type Endpoint11_0Input = {
  readonly projectID: Endpoint11_0Request["params"]["projectID"]
  readonly location?: Endpoint11_0Request["query"]["location"]
  readonly strategy: Endpoint11_0Request["payload"]["strategy"]
  readonly directory: Endpoint11_0Request["payload"]["directory"]
  readonly name?: Endpoint11_0Request["payload"]["name"]
}
const Endpoint11_0 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint11_0Input) =>
  raw["projectCopy.create"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { strategy: input["strategy"], directory: input["directory"], name: input["name"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint11_1Request = Parameters<RawClient["server.projectCopy"]["projectCopy.remove"]>[0]
type Endpoint11_1Input = {
  readonly projectID: Endpoint11_1Request["params"]["projectID"]
  readonly location?: Endpoint11_1Request["query"]["location"]
  readonly directory: Endpoint11_1Request["payload"]["directory"]
  readonly force: Endpoint11_1Request["payload"]["force"]
}
const Endpoint11_1 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint11_1Input) =>
  raw["projectCopy.remove"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { directory: input["directory"], force: input["force"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint11_2Request = Parameters<RawClient["server.projectCopy"]["projectCopy.refresh"]>[0]
type Endpoint11_2Input = {
  readonly projectID: Endpoint11_2Request["params"]["projectID"]
  readonly location?: Endpoint11_2Request["query"]["location"]
}
const Endpoint11_2 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint11_2Input) =>
  raw["projectCopy.refresh"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup11 = (raw: RawClient["server.projectCopy"]) => ({
  create: Endpoint11_0(raw),
  remove: Endpoint11_1(raw),
  refresh: Endpoint11_2(raw),
})

const Endpoint12_0 = (raw: RawClient["server.memory"]) => () =>
  raw["memory.wings"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint12_1Request = Parameters<RawClient["server.memory"]["memory.wing"]>[0]
type Endpoint12_1Input = {
  readonly kind: Endpoint12_1Request["payload"]["kind"]
  readonly key: Endpoint12_1Request["payload"]["key"]
  readonly name: Endpoint12_1Request["payload"]["name"]
}
const Endpoint12_1 = (raw: RawClient["server.memory"]) => (input: Endpoint12_1Input) =>
  raw["memory.wing"]({ payload: { kind: input["kind"], key: input["key"], name: input["name"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint12_2Request = Parameters<RawClient["server.memory"]["memory.rooms"]>[0]
type Endpoint12_2Input = { readonly wingID: Endpoint12_2Request["query"]["wingID"] }
const Endpoint12_2 = (raw: RawClient["server.memory"]) => (input: Endpoint12_2Input) =>
  raw["memory.rooms"]({ query: { wingID: input["wingID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint12_3Request = Parameters<RawClient["server.memory"]["memory.room"]>[0]
type Endpoint12_3Input = {
  readonly wingID: Endpoint12_3Request["payload"]["wingID"]
  readonly slug: Endpoint12_3Request["payload"]["slug"]
  readonly name: Endpoint12_3Request["payload"]["name"]
}
const Endpoint12_3 = (raw: RawClient["server.memory"]) => (input: Endpoint12_3Input) =>
  raw["memory.room"]({ payload: { wingID: input["wingID"], slug: input["slug"], name: input["name"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint12_4Request = Parameters<RawClient["server.memory"]["memory.list"]>[0]
type Endpoint12_4Input = {
  readonly wingID: Endpoint12_4Request["query"]["wingID"]
  readonly roomID?: Endpoint12_4Request["query"]["roomID"]
}
const Endpoint12_4 = (raw: RawClient["server.memory"]) => (input: Endpoint12_4Input) =>
  raw["memory.list"]({ query: { wingID: input["wingID"], roomID: input["roomID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint12_5Request = Parameters<RawClient["server.memory"]["memory.create"]>[0]
type Endpoint12_5Input = {
  readonly wingID: Endpoint12_5Request["payload"]["wingID"]
  readonly roomID: Endpoint12_5Request["payload"]["roomID"]
  readonly kind: Endpoint12_5Request["payload"]["kind"]
  readonly title: Endpoint12_5Request["payload"]["title"]
  readonly body: Endpoint12_5Request["payload"]["body"]
  readonly anchor?: Endpoint12_5Request["payload"]["anchor"]
  readonly validFrom?: Endpoint12_5Request["payload"]["validFrom"]
  readonly supersedes?: Endpoint12_5Request["payload"]["supersedes"]
}
const Endpoint12_5 = (raw: RawClient["server.memory"]) => (input: Endpoint12_5Input) =>
  raw["memory.create"]({
    payload: {
      wingID: input["wingID"],
      roomID: input["roomID"],
      kind: input["kind"],
      title: input["title"],
      body: input["body"],
      anchor: input["anchor"],
      validFrom: input["validFrom"],
      supersedes: input["supersedes"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint12_6Request = Parameters<RawClient["server.memory"]["memory.update"]>[0]
type Endpoint12_6Input = {
  readonly drawerID: Endpoint12_6Request["params"]["drawerID"]
  readonly expectedTimeUpdated: Endpoint12_6Request["payload"]["expectedTimeUpdated"]
  readonly wingID: Endpoint12_6Request["payload"]["wingID"]
  readonly roomID: Endpoint12_6Request["payload"]["roomID"]
  readonly kind: Endpoint12_6Request["payload"]["kind"]
  readonly title: Endpoint12_6Request["payload"]["title"]
  readonly body: Endpoint12_6Request["payload"]["body"]
  readonly anchor?: Endpoint12_6Request["payload"]["anchor"]
}
const Endpoint12_6 = (raw: RawClient["server.memory"]) => (input: Endpoint12_6Input) =>
  raw["memory.update"]({
    params: { drawerID: input["drawerID"] },
    payload: {
      expectedTimeUpdated: input["expectedTimeUpdated"],
      wingID: input["wingID"],
      roomID: input["roomID"],
      kind: input["kind"],
      title: input["title"],
      body: input["body"],
      anchor: input["anchor"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint12_7Request = Parameters<RawClient["server.memory"]["memory.remove"]>[0]
type Endpoint12_7Input = {
  readonly drawerID: Endpoint12_7Request["params"]["drawerID"]
  readonly wingID: Endpoint12_7Request["query"]["wingID"]
}
const Endpoint12_7 = (raw: RawClient["server.memory"]) => (input: Endpoint12_7Input) =>
  raw["memory.remove"]({ params: { drawerID: input["drawerID"] }, query: { wingID: input["wingID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup12 = (raw: RawClient["server.memory"]) => ({
  wings: Endpoint12_0(raw),
  wing: Endpoint12_1(raw),
  rooms: Endpoint12_2(raw),
  room: Endpoint12_3(raw),
  list: Endpoint12_4(raw),
  create: Endpoint12_5(raw),
  update: Endpoint12_6(raw),
  remove: Endpoint12_7(raw),
})

type Endpoint13_0Request = Parameters<RawClient["server.loop"]["loop.create"]>[0]
type Endpoint13_0Input = {
  readonly name: Endpoint13_0Request["payload"]["name"]
  readonly prompt: Endpoint13_0Request["payload"]["prompt"]
  readonly location?: Endpoint13_0Request["payload"]["location"]
  readonly agent?: Endpoint13_0Request["payload"]["agent"]
  readonly model?: Endpoint13_0Request["payload"]["model"]
  readonly skill?: Endpoint13_0Request["payload"]["skill"]
  readonly workflow?: Endpoint13_0Request["payload"]["workflow"]
  readonly intervalSeconds?: Endpoint13_0Request["payload"]["intervalSeconds"]
  readonly cronExpression?: Endpoint13_0Request["payload"]["cronExpression"]
  readonly timezone?: Endpoint13_0Request["payload"]["timezone"]
  readonly startsAt?: Endpoint13_0Request["payload"]["startsAt"]
  readonly expiresAt?: Endpoint13_0Request["payload"]["expiresAt"]
  readonly paused?: Endpoint13_0Request["payload"]["paused"]
  readonly eventTrigger?: Endpoint13_0Request["payload"]["eventTrigger"]
}
const Endpoint13_0 = (raw: RawClient["server.loop"]) => (input: Endpoint13_0Input) =>
  raw["loop.create"]({
    payload: {
      name: input["name"],
      prompt: input["prompt"],
      location: input["location"],
      agent: input["agent"],
      model: input["model"],
      skill: input["skill"],
      workflow: input["workflow"],
      intervalSeconds: input["intervalSeconds"],
      cronExpression: input["cronExpression"],
      timezone: input["timezone"],
      startsAt: input["startsAt"],
      expiresAt: input["expiresAt"],
      paused: input["paused"],
      eventTrigger: input["eventTrigger"],
    },
  }).pipe(Effect.mapError(mapClientError))

const Endpoint13_1 = (raw: RawClient["server.loop"]) => () => raw["loop.list"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint13_2Request = Parameters<RawClient["server.loop"]["loop.get"]>[0]
type Endpoint13_2Input = { readonly loopID: Endpoint13_2Request["params"]["loopID"] }
const Endpoint13_2 = (raw: RawClient["server.loop"]) => (input: Endpoint13_2Input) =>
  raw["loop.get"]({ params: { loopID: input["loopID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint13_3Request = Parameters<RawClient["server.loop"]["loop.edit"]>[0]
type Endpoint13_3Input = {
  readonly loopID: Endpoint13_3Request["params"]["loopID"]
  readonly name?: Endpoint13_3Request["payload"]["name"]
  readonly prompt?: Endpoint13_3Request["payload"]["prompt"]
  readonly intervalSeconds?: Endpoint13_3Request["payload"]["intervalSeconds"]
  readonly cronExpression?: Endpoint13_3Request["payload"]["cronExpression"]
  readonly timezone?: Endpoint13_3Request["payload"]["timezone"]
  readonly expiresAt?: Endpoint13_3Request["payload"]["expiresAt"]
  readonly agent?: Endpoint13_3Request["payload"]["agent"]
  readonly model?: Endpoint13_3Request["payload"]["model"]
  readonly skill?: Endpoint13_3Request["payload"]["skill"]
  readonly workflow?: Endpoint13_3Request["payload"]["workflow"]
  readonly eventTrigger?: Endpoint13_3Request["payload"]["eventTrigger"]
  readonly resetAgent?: Endpoint13_3Request["payload"]["resetAgent"]
  readonly resetModel?: Endpoint13_3Request["payload"]["resetModel"]
  readonly resetSkill?: Endpoint13_3Request["payload"]["resetSkill"]
}
const Endpoint13_3 = (raw: RawClient["server.loop"]) => (input: Endpoint13_3Input) =>
  raw["loop.edit"]({
    params: { loopID: input["loopID"] },
    payload: {
      name: input["name"],
      prompt: input["prompt"],
      intervalSeconds: input["intervalSeconds"],
      cronExpression: input["cronExpression"],
      timezone: input["timezone"],
      expiresAt: input["expiresAt"],
      agent: input["agent"],
      model: input["model"],
      skill: input["skill"],
      workflow: input["workflow"],
      eventTrigger: input["eventTrigger"],
      resetAgent: input["resetAgent"],
      resetModel: input["resetModel"],
      resetSkill: input["resetSkill"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint13_4Request = Parameters<RawClient["server.loop"]["loop.pause"]>[0]
type Endpoint13_4Input = { readonly loopID: Endpoint13_4Request["params"]["loopID"] }
const Endpoint13_4 = (raw: RawClient["server.loop"]) => (input: Endpoint13_4Input) =>
  raw["loop.pause"]({ params: { loopID: input["loopID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint13_5Request = Parameters<RawClient["server.loop"]["loop.resume"]>[0]
type Endpoint13_5Input = { readonly loopID: Endpoint13_5Request["params"]["loopID"] }
const Endpoint13_5 = (raw: RawClient["server.loop"]) => (input: Endpoint13_5Input) =>
  raw["loop.resume"]({ params: { loopID: input["loopID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint13_6Request = Parameters<RawClient["server.loop"]["loop.delete"]>[0]
type Endpoint13_6Input = { readonly loopID: Endpoint13_6Request["params"]["loopID"] }
const Endpoint13_6 = (raw: RawClient["server.loop"]) => (input: Endpoint13_6Input) =>
  raw["loop.delete"]({ params: { loopID: input["loopID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint13_7Request = Parameters<RawClient["server.loop"]["loop.runNow"]>[0]
type Endpoint13_7Input = { readonly loopID: Endpoint13_7Request["params"]["loopID"] }
const Endpoint13_7 = (raw: RawClient["server.loop"]) => (input: Endpoint13_7Input) =>
  raw["loop.runNow"]({ params: { loopID: input["loopID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint13_8Request = Parameters<RawClient["server.loop"]["loop.runList"]>[0]
type Endpoint13_8Input = { readonly loopID: Endpoint13_8Request["params"]["loopID"] }
const Endpoint13_8 = (raw: RawClient["server.loop"]) => (input: Endpoint13_8Input) =>
  raw["loop.runList"]({ params: { loopID: input["loopID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint13_9Request = Parameters<RawClient["server.loop"]["loop.runGet"]>[0]
type Endpoint13_9Input = {
  readonly loopID: Endpoint13_9Request["params"]["loopID"]
  readonly runID: Endpoint13_9Request["params"]["runID"]
}
const Endpoint13_9 = (raw: RawClient["server.loop"]) => (input: Endpoint13_9Input) =>
  raw["loop.runGet"]({ params: { loopID: input["loopID"], runID: input["runID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint13_10Request = Parameters<RawClient["server.loop"]["loop.runCancel"]>[0]
type Endpoint13_10Input = {
  readonly loopID: Endpoint13_10Request["params"]["loopID"]
  readonly runID: Endpoint13_10Request["params"]["runID"]
}
const Endpoint13_10 = (raw: RawClient["server.loop"]) => (input: Endpoint13_10Input) =>
  raw["loop.runCancel"]({ params: { loopID: input["loopID"], runID: input["runID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup13 = (raw: RawClient["server.loop"]) => ({
  create: Endpoint13_0(raw),
  list: Endpoint13_1(raw),
  get: Endpoint13_2(raw),
  edit: Endpoint13_3(raw),
  pause: Endpoint13_4(raw),
  resume: Endpoint13_5(raw),
  delete: Endpoint13_6(raw),
  runNow: Endpoint13_7(raw),
  runList: Endpoint13_8(raw),
  runGet: Endpoint13_9(raw),
  runCancel: Endpoint13_10(raw),
})

type Endpoint14_0Request = Parameters<RawClient["server.intel"]["intel.advisories"]>[0]
type Endpoint14_0Input = {
  readonly page?: Endpoint14_0Request["query"]["page"]
  readonly pageSize?: Endpoint14_0Request["query"]["pageSize"]
  readonly severity?: Endpoint14_0Request["query"]["severity"]
  readonly search?: Endpoint14_0Request["query"]["search"]
  readonly sort?: Endpoint14_0Request["query"]["sort"]
  readonly order?: Endpoint14_0Request["query"]["order"]
}
const Endpoint14_0 = (raw: RawClient["server.intel"]) => (input?: Endpoint14_0Input) =>
  raw["intel.advisories"]({
    query: {
      page: input?.["page"],
      pageSize: input?.["pageSize"],
      severity: input?.["severity"],
      search: input?.["search"],
      sort: input?.["sort"],
      order: input?.["order"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint14_1Request = Parameters<RawClient["server.intel"]["intel.kev"]>[0]
type Endpoint14_1Input = {
  readonly page?: Endpoint14_1Request["query"]["page"]
  readonly pageSize?: Endpoint14_1Request["query"]["pageSize"]
  readonly sort?: Endpoint14_1Request["query"]["sort"]
  readonly order?: Endpoint14_1Request["query"]["order"]
}
const Endpoint14_1 = (raw: RawClient["server.intel"]) => (input?: Endpoint14_1Input) =>
  raw["intel.kev"]({
    query: { page: input?.["page"], pageSize: input?.["pageSize"], sort: input?.["sort"], order: input?.["order"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint14_2Request = Parameters<RawClient["server.intel"]["intel.news"]>[0]
type Endpoint14_2Input = {
  readonly page?: Endpoint14_2Request["query"]["page"]
  readonly pageSize?: Endpoint14_2Request["query"]["pageSize"]
  readonly sort?: Endpoint14_2Request["query"]["sort"]
  readonly order?: Endpoint14_2Request["query"]["order"]
}
const Endpoint14_2 = (raw: RawClient["server.intel"]) => (input?: Endpoint14_2Input) =>
  raw["intel.news"]({
    query: { page: input?.["page"], pageSize: input?.["pageSize"], sort: input?.["sort"], order: input?.["order"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint14_3Request = Parameters<RawClient["server.intel"]["intel.trends"]>[0]
type Endpoint14_3Input = { readonly days?: Endpoint14_3Request["query"]["days"] }
const Endpoint14_3 = (raw: RawClient["server.intel"]) => (input?: Endpoint14_3Input) =>
  raw["intel.trends"]({ query: { days: input?.["days"] } }).pipe(Effect.mapError(mapClientError))

const Endpoint14_4 = (raw: RawClient["server.intel"]) => () =>
  raw["intel.feeds"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint14_5Request = Parameters<RawClient["server.intel"]["intel.feedAdd"]>[0]
type Endpoint14_5Input = {
  readonly id?: Endpoint14_5Request["payload"]["id"]
  readonly name: Endpoint14_5Request["payload"]["name"]
  readonly kind: Endpoint14_5Request["payload"]["kind"]
  readonly url: Endpoint14_5Request["payload"]["url"]
  readonly enabled?: Endpoint14_5Request["payload"]["enabled"]
}
const Endpoint14_5 = (raw: RawClient["server.intel"]) => (input: Endpoint14_5Input) =>
  raw["intel.feedAdd"]({
    payload: {
      id: input["id"],
      name: input["name"],
      kind: input["kind"],
      url: input["url"],
      enabled: input["enabled"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint14_6Request = Parameters<RawClient["server.intel"]["intel.feedUpdate"]>[0]
type Endpoint14_6Input = {
  readonly feedID: Endpoint14_6Request["params"]["feedID"]
  readonly name?: Endpoint14_6Request["payload"]["name"]
  readonly kind?: Endpoint14_6Request["payload"]["kind"]
  readonly url?: Endpoint14_6Request["payload"]["url"]
  readonly enabled?: Endpoint14_6Request["payload"]["enabled"]
}
const Endpoint14_6 = (raw: RawClient["server.intel"]) => (input: Endpoint14_6Input) =>
  raw["intel.feedUpdate"]({
    params: { feedID: input["feedID"] },
    payload: { name: input["name"], kind: input["kind"], url: input["url"], enabled: input["enabled"] },
  }).pipe(Effect.mapError(mapClientError))

const Endpoint14_7 = (raw: RawClient["server.intel"]) => () =>
  raw["intel.feedsReset"]({}).pipe(Effect.mapError(mapClientError))

const Endpoint14_8 = (raw: RawClient["server.intel"]) => () =>
  raw["intel.status"]({}).pipe(Effect.mapError(mapClientError))

const Endpoint14_9 = (raw: RawClient["server.intel"]) => () =>
  raw["intel.poll"]({}).pipe(Effect.mapError(mapClientError))

const adaptGroup14 = (raw: RawClient["server.intel"]) => ({
  advisories: Endpoint14_0(raw),
  kev: Endpoint14_1(raw),
  news: Endpoint14_2(raw),
  trends: Endpoint14_3(raw),
  feeds: Endpoint14_4(raw),
  feedAdd: Endpoint14_5(raw),
  feedUpdate: Endpoint14_6(raw),
  feedsReset: Endpoint14_7(raw),
  status: Endpoint14_8(raw),
  poll: Endpoint14_9(raw),
})

type Endpoint15_0Request = Parameters<RawClient["server.whiteboard"]["whiteboard.get"]>[0]
type Endpoint15_0Input = { readonly sessionID: Endpoint15_0Request["params"]["sessionID"] }
const Endpoint15_0 = (raw: RawClient["server.whiteboard"]) => (input: Endpoint15_0Input) =>
  raw["whiteboard.get"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint15_1Request = Parameters<RawClient["server.whiteboard"]["whiteboard.update"]>[0]
type Endpoint15_1Input = {
  readonly sessionID: Endpoint15_1Request["params"]["sessionID"]
  readonly patch: Endpoint15_1Request["payload"]["patch"]
  readonly clientID: Endpoint15_1Request["payload"]["clientID"]
  readonly username: Endpoint15_1Request["payload"]["username"]
}
const Endpoint15_1 = (raw: RawClient["server.whiteboard"]) => (input: Endpoint15_1Input) =>
  raw["whiteboard.update"]({
    params: { sessionID: input["sessionID"] },
    payload: { patch: input["patch"], clientID: input["clientID"], username: input["username"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint15_2Request = Parameters<RawClient["server.whiteboard"]["whiteboard.presence"]>[0]
type Endpoint15_2Input = {
  readonly sessionID: Endpoint15_2Request["params"]["sessionID"]
  readonly clientID: Endpoint15_2Request["payload"]["clientID"]
  readonly username: Endpoint15_2Request["payload"]["username"]
  readonly pointer?: Endpoint15_2Request["payload"]["pointer"]
  readonly selectedElementIds?: Endpoint15_2Request["payload"]["selectedElementIds"]
}
const Endpoint15_2 = (raw: RawClient["server.whiteboard"]) => (input: Endpoint15_2Input) =>
  raw["whiteboard.presence"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      clientID: input["clientID"],
      username: input["username"],
      pointer: input["pointer"],
      selectedElementIds: input["selectedElementIds"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint15_3Request = Parameters<RawClient["server.whiteboard"]["whiteboard.events"]>[0]
type Endpoint15_3Input = { readonly sessionID: Endpoint15_3Request["params"]["sessionID"] }
const Endpoint15_3 = (raw: RawClient["server.whiteboard"]) => (input: Endpoint15_3Input) =>
  Stream.unwrap(
    raw["whiteboard.events"]({ params: { sessionID: input["sessionID"] } }).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

const adaptGroup15 = (raw: RawClient["server.whiteboard"]) => ({
  get: Endpoint15_0(raw),
  update: Endpoint15_1(raw),
  presence: Endpoint15_2(raw),
  events: Endpoint15_3(raw),
})

const adaptClient = (raw: RawClient) => ({
  health: adaptGroup0(raw["server.health"]),
  location: adaptGroup1(raw["server.location"]),
  agents: adaptGroup2(raw["server.agent"]),
  sessions: adaptGroup3(raw["server.session"]),
  messages: adaptGroup4(raw["server.message"]),
  permissions: adaptGroup5(raw["server.permission"]),
  files: adaptGroup6(raw["server.fs"]),
  commands: adaptGroup7(raw["server.command"]),
  events: adaptGroup8(raw["server.event"]),
  ptys: adaptGroup9(raw["server.pty"]),
  questions: adaptGroup10(raw["server.question"]),
  projectCopies: adaptGroup11(raw["server.projectCopy"]),
  memories: adaptGroup12(raw["server.memory"]),
  loops: adaptGroup13(raw["server.loop"]),
  "server.intel": adaptGroup14(raw["server.intel"]),
  "server.whiteboard": adaptGroup15(raw["server.whiteboard"]),
})

export const make = (options?: { readonly baseUrl?: URL | string }) =>
  HttpApiClient.make(ClientApi, options).pipe(Effect.map(adaptClient))
