// @generated by @turenlabs/httpapi-codegen. Do not edit.

import { Schema } from "effect"

export class ClientError extends Schema.TaggedErrorClass<ClientError>()("ClientError", {
  cause: Schema.Defect(),
}) {}
