import { NodeFileSystem } from "@effect/platform-node"
import { compile, emitEffectImported, emitPromise, write } from "@turenlabs/httpapi-codegen"
import { ClientApi, endpointNames, groupNames, omitEndpoints } from "../src/contract"
import { Effect } from "effect"
import { fileURLToPath } from "url"

const contract = compile(ClientApi, { groupNames, endpointNames, omitEndpoints })
const generated = (output: ReturnType<typeof emitPromise>) => ({
  ...output,
  files: output.files.map((file) => ({
    ...file,
    content: `// @generated by @turenlabs/httpapi-codegen. Do not edit.\n\n${file.content}`,
  })),
})

await Effect.runPromise(
  Effect.all(
    [
      write(
        generated(
          emitPromise(contract, {
            outputTypes: {
              "events.subscribe": {
                name: "ForgeEventEncoded",
                import: 'import type { ForgeEventEncoded } from "@turenlabs/protocol/groups/event"',
              },
            },
          }),
        ),
        fileURLToPath(new URL("../src/generated", import.meta.url)),
      ),
      write(
        generated(emitEffectImported(contract, { module: "../contract", api: "ClientApi" })),
        fileURLToPath(new URL("../src/generated-effect", import.meta.url)),
      ),
    ],
    { concurrency: 2, discard: true },
  ).pipe(Effect.provide(NodeFileSystem.layer)),
)
